### ISSUE TITLE
Journey API doesn't return an error when datetime is not provided

### ISSUE THREAD

**Issue by RaitoBezarius** [hove-io/navitia#1041]
Hi,

According to the documentation, the journey API requires that a datetime is provided in the call.

But the truth is that the journey API will silently proceed even without any datetime, returning some default datetime for departure: 13:XX.

I didn't try to see what can be done with this bug.
EDIT: https://github.com/CanalTP/navitia/blob/df3523038e601b1472551141f90d6ba303ed4145/source/jormungandr/jormungandr/interfaces/v1/Journeys.py#L517
It seems to be the line which cause this bug. A `required` attribute might be missing here?

But it would be cool to return an error that the parameter required is not provided.

**Comment by antoine-de** [comment]
Hi @RaitoBezarius,

historically we used leet hour (13:37) as the default datetime.

As you said the param should be mandatory (and it is said to be in the doc), but we fear to break some integrations as it is so for quite a long time.

We are discussing the pros and cons of updating the doc vs updating the code. We'll update this issue when the discussion will be closed.

Nice project btw, I didn't know wannago.

**Comment by RaitoBezarius** [comment]
Oh, I understand why, now. Anyway, thanks for your clarification !
Haha, thanks for wannago !
