### ISSUE TITLE
Error when building Navitia

### ISSUE THREAD

**Issue by kalon33** [hove-io/navitia#1164]
When trying to build Navitia, I have this error:

CMake Error at type/CMakeLists.txt:118 (add_executable):
  Cannot find source file:

```
tests/code_container_test.cpp
```

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx

Could you have a look at this?

Thanks.

**Comment by TeXitoi** [comment]
This file is here : source/type/tests/code_container_test.cpp

Seems OK, and it compiles in our CI. Are you up to date? Can we have more information on your environment? (linux version, gcc version, cmake version, ...)

**Comment by kalon33** [comment]
Yes, I'm up to date to latest git. I'm building on Ubuntu Trusty, in a build-daemon, using the code I mirrored here: https://code.launchpad.net/~kalon33/+junk/navitia . The only things I changed is debian/control and debian/rules to fix errors in them. It used to build a week ago.

Here is the whole build log: https://code.launchpad.net/~kalon33/+archive/ubuntu/experimental-stuff/+build/7886277/+files/buildlog_ubuntu-trusty-amd64.navitia2_1.25.0-1%2Bgit201509081205%7Eubuntu14.04.1_BUILDING.txt.gz

**Comment by TeXitoi** [comment]
Do you have source/type/tests/code_container_test.cpp in your source archive? This file was added not so long ago. Maybe the new file was not included in the archive?

**Comment by kalon33** [comment]
Thanks @TeXitoi , that's exactly what happened. Bazaar requires you explicitly add new files and when I refreshed the files from git, it only picked up the ones that were updated and not the newly created ones. Hopefully that will fix building in my repository.

Thanks for your help :)
