### ISSUE TITLE
NTFS format name - confusing with de File System ?

### ISSUE THREAD

**Issue by prhod** [hove-io/navitia#1373]
Several persons told me that the format name "NTFS" colides with the File System and that we should change the name.
Do you agree ?

**Comment by antoine-de** [comment]
completely!

**Comment by stifoon** [comment]
completely!

**Comment by stifoon** [comment]
- Navitia Feed Specification : "NaFiSpia"
- "krill" (to feed Kraken)
- "chocolate" (to feed me)

**Comment by prhod** [comment]
If you want to feed the Kraken, what do you think of : 
Formated Input for the System Hosted (ie. FISH ^^ )

**Comment by stifoon** [comment]
Mackerel?

**Comment by pbougue** [comment]
INK : Input for Navitia and Kraken ?

**Comment by antoine-de** [comment]
In a less fun area, I really think that having a input file format different from the GTFS is a break to Navitia's reuse.

To show a bit that the NTFS is not very far from the GTFS (and maybe one day it might converge with it \o/), maybe it will be nice to choose a name not far from GTFS ?

not very inspired, but XTFS (eXtended TFS) ? ETFS ? xGTFS ?

**Comment by cboxL** [comment]
GNAK => Gtfs for Navitia And Kraken
DANTFS => Digitally Advanced Navitia Transit Feed Specification

**Comment by kinnou02** [comment]
We won't change it now...
I close this issue.
