### ISSUE TITLE
Add physical_mode to departures and stop_schedules

### ISSUE THREAD

**Issue by grote** [hove-io/navitia#1386]
When querying for [departures](https://github.com/CanalTP/navitia/blob/dev/documentation/navitia.io/source/integration.rst#departures-departures) I need to know the physical mode of each departure to show it properly in my app.

Would it be possible to include a [`physical_mode` object](https://github.com/CanalTP/navitia/blob/dev/documentation/navitia.io/source/integration.rst#physical-mode) in the response to `departures` and `stop_schedules` queries?

Alternatively, I could of course make separate requests to get the physical mode for _each_ 
departure. But I guess it is also in your interest to not require users to make unnecessary excessive queries to your service.

**Comment by grote** [comment]
Has this secretly been fixed?

A query like this `http://api.navitia.io/v1/coverage/fr-idf/stop_areas/stop_area:OIF:SA:8775862/departures?from_datetime=20160519T223512&count=12&duration=86400&depth=0` now returns a list of departures that has a `route` and in this route seem always to be `physical_modes` like this:

``` json
                "physical_modes": [
                    {
                        "id": "physical_mode:Bus",
                        "name": "Bus"
                    }
                ]
```

``` json
                "physical_modes": [
                    {
                        "id": "physical_mode:RapidTransit",
                        "name": "Train de banlieue / RER"
                    }
                ]
```

Is this now reliable and stable for all `/departures` queries?

**Comment by pbougue** [comment]
I'd say stable, but not fully reliable.

We added this to `route` objects, and this information is "most of the time" true. That is to say when a route only uses one `physical_mode`, it's true (as we only retrieve the first `physical_mode` linked to that route).
In the ideal model of the real world, this information linked to a route is a list, but in the real world it would be hard to find an instance where there are multiple `physical_modes`.

What you really want if I understand well is the `departures/display_information/physical_mode` to be an id and not a name (this information is reliable, as it is linked to the vehicle_journey). If so we will have a look to see if it's doable and how.

**Comment by grote** [comment]
As long as every departure query gives me a `route` object that contains the physical mode of that departure I am happy and consider this issue resolved. I've never seen a line with two different physical modes in the wild.

The problem was that this information was sometimes there in the display information, but not reliable as it could not always be mapped to the officially supported physical modes.

**Comment by pbougue** [comment]
If it's Ok for you, then I close this issue.

I did a little mistake, as we have a `physical_mode` list in `route`, so the information is reliable (but hard to read into if you have more than one mode).

We might look into enriching `departures/display_information` with a physical_mode id somehow, but not sure we will do, as this seems enough as it is.
Don't hesitate to reopen and we would probably look into that solution.
