### ISSUE TITLE
Codec error when utf8 characters in filter

### ISSUE THREAD

**Issue by eturck** [hove-io/navitia#1417]
Hello,

We talked a little bit about it with @stifoon and @kinnou02 this morning on the phone.
If I do a request on api.navitia.io for the line 22bis with a filter on the code (https://api.navitia.io/v1/coverage/fr-idf/lines?filter=line.code=22bis&depth=0) I have a result : 

``` javascript
{
    code: "22bis",
    name: "22bis Marché",
    closing_time: "112500",
    opening_time: "083500",
    id: "line:OIF:067067022:22bisOIF376"
}
```

But if I want to filter on the name (https://api.navitia.io/v1/coverage/fr-idf/lines?filter=line.name="22bis%20March%C3%A9"&depth=0) I have an error :

``` javascript
{
    message: "'ascii' codec can't encode character u'\xe9' in position 21: ordinal not in range(128)"
}
```

I have the same problem on my local navitia instance, mainly when I want to filter by network name, since our network is called Tisséo. I use python 2.7.
In https://github.com/CanalTP/navitia/blob/dev/source/jormungandr/jormungandr/interfaces/v1/Uri.py#L106 I tried to change : 

``` python
if is_collection:
    parser.add_argument("filter", type=str, default="", description="The filter parameter")
```

To : 

``` python
if is_collection:
    parser.add_argument("filter", type=unicode, default="", description="The filter parameter")
```

It seems to work, I just need to use double quotes, but I think it's normal :
http://<server>/v1/coverage/tisseo/lines?filter=network.name=Tisséo => doesn't work (Unable to parse :Filter: Unable to parse the whole string. Not parsed: >>éo<<")
http://<server>/v1/coverage/tisseo/lines?filter=network.name="Tisséo" => :+1: 

I'm not sure the fix is that simple, but that is what I found :).

**Comment by kinnou02** [comment]
If you use filter directly you effectively have to quote. for what you want you also could do this: 

```
http://<server>/v1/coverage/tisseo/networks/network:Tisséo/lines
```

where network:Tisséo is the uri of your network, we don't recommand using filter directly, it's mandatory for some request, but a lot of thing can be expressed directly in the url.

You fix is the good one, it's seem we have forgotten some parameter.
The PR is coming.

**Comment by eturck** [comment]
We're doing some strange things to map our current API to kraken, and we have a filter by network name.
My URI is network:1, and only the name is Tisséo, that's why I was trying to use the filter directly.

Thank you for the quick fix :).
