### ISSUE TITLE
Location Names from OpenStreetMap start with lower case

### ISSUE THREAD

**Issue by grote** [hove-io/navitia#1469]
When autocompleting locations from OpenStreetMap they always start with a lowercase letter like:
`Rue De Verdun (melun)`
The first letter should be upper-case instead.

**Comment by antoine-de** [comment]
strange, when I query:
`https://api.navitia.io/v1/coverage/fr-idf/places?q=Rue%20De%20Verdun%20me`

I got:

`"name": "Rue de Verdun (Melun)",`

What call are you doing ?

**Comment by grote** [comment]
I'm sorry! I assumed Navitia would return the String like this without doing deeper debugging. Turns out my assumption was wrong. Sorry for the noise!
