### ISSUE TITLE
Get departures from coordinates

### ISSUE THREAD

**Issue by fische** [hove-io/navitia#1651]
Hey !

I tried to do the following request :
`curl https://api.navitia.io/v1/coverage/-0.08609;51.50502/departures?from_datetime=20160815T133700 --header 'Authorization: ****'`

From this request, I get an error 400 and the following body:

``` JSON
{
  "message": "Invalid arguments filter",
  "error": {
    "message": "Invalid arguments filter",
    "id": "unknown_object"
  }
}
```

I checked the [documentation](http://doc.navitia.io/#departures) and my request should be good. So where am I wrong ?

**Comment by pbougue** [comment]
Hello,

It seems that the doc is having a problem (and the API also...)
2 bugs with 1 request, that's an issue we like :)
A working request for what you seem to be willing is: `https://api.navitia.io/v1/coverage/uk/coord/-0.08609%3B51.50502/departures?from_datetime=20160815T133700&`
We will try to update the doc soon, and also to have a look at the API, as this doesn't seems to always work as expected, for the `coords` management.

**Comment by fische** [comment]
Thanks for the quick response !

So if I understand it well, there's no way, for the moment, to get departures from the nearby stations only by providing latitude and longitude ? I have to use region ID with these coordinates, do I ?

**Comment by pbougue** [comment]
Ok, we spoke today and for now, and if you don't want to provide coverage name, you have to provide coordinates 2 times : `https://api.navitia.io/v1/coverage/-0.08609%3B51.50502/coord/-0.08609%3B51.50502/departures?from_datetime=20160815T133700`
We have to improve that, but there is a way without coverage name ;)

**Comment by kadhikari** [comment]
Hi,
As explained by @pbougue and corrected in the doc http://doc.navitia.io/#departures , a request with coord works well and there will not be any improvement on short term. 

Your request with some modifications looks like: https://api.navitia.io/v1/coverage/-0.08609%3B51.50502/coords/-0.08609%3B51.50502/departures?from_datetime=20170502T133700
