### ISSUE TITLE
Boarding / Alighting time in navitia

### ISSUE THREAD

**Issue by eturck** [hove-io/navitia#1662]
Hello!

Following our discussions about the modelization of our On Demand Transport network at Tisséo, it became pretty clear that we need to use boarding time / alighting time. This issue is here to centralize questions and list choices made for every step of the development.
### The problem

At Tisséo we need to have a departure time earlier than the arrival time in order to modelize a service passing at a stop sometime during a time frame of 10 minutes. We know that the client is able to board at the earliest at T - 10 minutes and is able to get off at the latest at T. It's currently impossible in navitia to have a departure_time smaller than the arrival_time.
### The solution

Boarding times! The simplest way to modelize what we want is to have the service passing by the stop at a time T, but with a boarding time of 10 minutes. This way the client would need to be at the stop a T - 10 minutes to be able to board. Alighting time is the same concept for the arrival.
Overall it could be something needed to represent extra time needed to go through security lanes for planes or trains, or to disembark from a ship.
### Name choices

The first question is what word to use to describe the opposite of boarding, "boarding" is pretty obvious and widely used, but I didn't find a clear opposite. I use "alighting" in the rest of this issue, [I chose to trust OpenTripPlanner](http://docs.opentripplanner.org/en/latest/Configuration/#boarding-and-alighting-times) :).
There is two places where we need to choose names : 
- NTFS : Add two optional fields to [stop_times.txt](https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_0.6.md#stop_timestxt-requis) representing time to board and time to get off the vehicle. I will let @prhod choose the names but I propose
  - boarding_duration : time in second to board (greater than or equal to 0),
  - alighting_duration : time in second to get off (greater than or equal to 0)
- In Navitia. After a quick discussion with @stifoon and @kinnou02 on monday it was prefered to store directly the "new" departure / arrival time (i.e. not just boarding_duration  but departure_time - boarding_duration). I don't really know what to use as names in ed database and in the code, but maybe boarding_time, alighting_time?
### Question time!

I'm not really far in the development of this feature but I already have a few questions : 
1. If we have a departure_time at 0h01 UTC, its departure_time will be 60 in the database, if we have a boarding_duration of 10 minutes, can I store a negative value as the boarding_time without any problem?
2. After importing NTFS datas I need to check if everything is correct. Do you have more ideas on what to check other than : 
   - Already existing : `(st1|st2).arrival_time <= (st1|st2).departure_time` (the bus arrives before departing)
   - Already existing : `st1.departure_time <= st2.arrival_time` (the bus arrives at the next stop after departing from the previous one)
   - `(st1|st2).boarding_time <= (st1|st2).departure_time` and `(st1|st2).alighting_time >= (st1|st2).arrival_time` (maybe useless if we store `(boarding|alighting)_duration` as unsigned integers, but make sure we're boarding before departing and alighting after arriving),
3. In gtfs_parser.cpp we make sure stop_times are correctly ordered with the check : `st1.departure_time <= st2.arrival_time`. I can't do that with boarding_time (i.e. `st1.boarding_time <= st2.alighting_time`), it doesn't really make sense, somebody could be ask to board at a stop before somebody at the preceding stop has finished the alighting process. Is this compatible with RAPTOR? Or abslutely not and I should still use departure / arrival times in RAPTOR and "correct" with boarding / alighting times maybe? (I guess I need to ping @TeXitoi on this one ;))

Let me know if I forgot anything. Writing my 3rd question made me realize I'm not to sure about the consequences of "replacing" departure_time by boarding_time in the algorithm like @stifoon suggested in his proposal. I fear that messing with the ordering will cause some trouble :), or maybe I just missed something and it's going to be super easy ;).

**Comment by TeXitoi** [comment]
For point 3, there is no problem. RAPTOR need that we cannot go out of the vehicle before getting in (i.e. time travel in the past). With the boarding model, it cannot be done.

**Comment by kinnou02** [comment]
Boarding_time and alighting_time seems fine to me.
For your first question, currently all times are stored as unsigned, so using negative value for for boarding_time will probably lead to some strange behavior, I think it's preferable to shift the vj and make it a past midnight. Almost all of the logic already exist for UTC, it's shouldn't be too hard to do.

**Comment by prhod** [comment]
Boarding_time and alighting_time are ok. I'll introduce them in the 0.6.2 version with the fare info.

**Comment by prhod** [comment]
I've added in the boarding_duration and alighting_duration fields to the NTFS 0.6.2 PR in progress
https://github.com/CanalTP/navitia/pull/1654/

**Comment by eturck** [comment]
Thank you @prhod and @kinnou02, I will use boarding and alighting time / duration and it seems pretty obvious to shift the vj now that you've said it :).

I have another question on stop_times.
Currently, we are sure that departure and arrival_time don't go back in time when the stop_sequence increase, with boarding and alighting duration it changes completely. Let's say with have a quick trip with four stops, here is the NTFS : 

| sequence | departure_time | arrival_time | boarding_duration | alighting_duration |
| --- | --- | --- | --- | --- |
| 0 | 08:00:00 | 08:00:00 | 0 | 0 |
| 1 | 08:05:00 | 08:04:00 | 0 | 15 |
| 2 | 08:10:00 | 08:08:00 | 15 | 5 |
| 3 | 08:15:00 | 08:14:00 | 0 | 0 |

When computing boarding and alighting_time we have : 

| order | boarding_time | departure_time | arrival_time | alighting_time |
| --- | --- | --- | --- | --- |
| 0 | 08:00:00 | 08:00:00 | 08:00:00 | 08:00:00 |
| 1 | 08:05:00 | 08:05:00 | 08:04:00 | 08:19:00 |
| 2 | 07:55:00 | 08:10:00 | 08:08:00 | 08:13:00 |
| 3 | 08:15:00 | 08:15:00 | 08:14:00 | 08:14:00 |

I don't see any reason not to accept something like this, different boarding and alighting duration depending on the stop_times seems plausible. Isn't this going to break a lot of things though? Since : 
- I can't say which is larger than the other,
- StopTimeGtfsHandler::finish order stop_times by their stop_sequence and make sure departure_time / arrival_time are correctly ordered, I can't check anything like that with boarding and alighting time, it's pretty obvious when looking at the table above,
- While reading the code of vj shifting I saw that we are getting the arrival_time of the stop_time with the smallest order to see if a vj has negative times. It makes sense since it's the smallest time possible for a vj currently. If I allow the modelisation above, I'm going to need to change that to get the minimum between the minimum boarding_time and the minimum arrival_time since I have no guarantee on the order of those time. Would it be the correct way? Is this assumption made in a lot of places?

At least, as @TeXitoi said, there is no time travel since, when considering two consecutive stop times st1 and st2, `st1.departure_time <= st2.arrival_time` is always true, and `st1.departure_time - boarding_duration <= st2.arrival_time + alighting_duration` will be too because durations are stored as unsigned integer.

Sorry I have a lot of questions. I really want to start in the right direction and don't want to make a bad choice in the beginning, but I feel like I'm going to break everything either way.

**Comment by pbougue** [comment]
Just for memory (we might have to elaborate a bit on that): the handler making sure that `st1.departure_time <= st2.departure_time` are correctly ordered shifts st2 one day in the future when there is a problem (managing pass-midnight vj). I don't know where it's done precisely, but you might have to change where it's done or the way it's done.

Otherwise, in my mind the raptor should be ok, and if there are problems, I guess the chances will be that the raptor implementation is not correct (for example using departure_time when it should use arrival_time), and we would more debug than have conceptual problems.

**Comment by TeXitoi** [comment]
@eturck I'm OK with all that you said. The only maybe assumed thing that may cause problems is that we may assume that the first stop time departure is in [0; 24h[ but I can't find where we do this assumption.

**Comment by pbougue** [comment]
@TeXitoi That may be the case indeed (I can't find where also), but this should be manageable.
The way I see this work, this is gonna be hard to split, so any occasion is good to

**Comment by stifoon** [comment]
Done ? https://github.com/CanalTP/navitia/pull/1980

**Comment by eturck** [comment]
Done ! :smile:

**Comment by stifoon** [comment]
\o/
