### ISSUE TITLE
[user feedback] Add timezones to output

### ISSUE THREAD

**Issue by pbougue** [hove-io/navitia#1706]
As this is standard this should not break many integrations, but still, that may need an extra field

**Comment by stifoon** [comment]
Duplicate https://github.com/CanalTP/navitia/issues/1799
All is collected here: https://github.com/CanalTP/navitia/wiki/Needs-for-a-version-2-of-the-API

**Comment by pbougue** [comment]
To precise a bit:
* not doable to add it to the fields we output now (this would definitely break some integrations), so only going into v2 requirements of the API.
* we are about to (I'd say a month or two) add extra context field to output current datetime and timezone of coverage, and that should cover this need (not as easily integrable as a proper timezoned datetime, but still)
