### ISSUE TITLE
Add line section disruptions management

### ISSUE THREAD

**Issue by pbougue** [hove-io/navitia#1775]
This issue is also a Chaos one : https://github.com/CanalTP/Chaos/issues/205
The goal is for the final user to avoid the full-line disruption, and to have it's journeys disrupted only when he uses the section.

**Comment by stifoon** [comment]
+1

**Comment by stifoon** [comment]
done ? https://github.com/CanalTP/navitia/pull/1991

**Comment by antoine-de** [comment]
yep, you're right
