### ISSUE TITLE
navitia does not compile on ubuntu 16.04

### ISSUE THREAD

**Issue by TeXitoi** [hove-io/navitia#1781]
The problem seems related to log4cplus not compiled in c++11. Compiling by hand log4cplus enabling c++11 should fix that, but that's not great.

Maybe we can fix that by changing our use of log4cplus.

```
CXXFLAGS=-std=c++11 ./configure
make
sudo make install
```

**Comment by TeXitoi** [comment]
https://bugs.launchpad.net/ubuntu/+source/log4cplus/+bug/1578970

**Comment by antoine-de** [comment]
should be fixed by now (cf ticket)
