### ISSUE TITLE
cleverage crashes

### ISSUE THREAD

**Issue by pbougue** [hove-io/navitia#1798]
probably due to some problems when reading cleverage fead, no try done
new relic link to add @kinnou02

**Comment by kinnou02** [comment]
https://rpm.newrelic.com/accounts/1336678/applications/23587422/traced_errors/a1e21038-8629-11e6-a90b-b82a72d22a14_13285_17503

**Comment by pbougue** [comment]
It's been done for some time now, closing the issue: https://github.com/CanalTP/navitia/blob/dev/source/jormungandr/jormungandr/schedule.py#L252
