### ISSUE TITLE
beta_endpoint features not working

### ISSUE THREAD

**Issue by vg-github** [hove-io/navitia#1820]
Is there a way to activate the heatmap feature in the self hosted version?

I get this message when I try to access a "beta_endpoint" feature:

> {"feed_publishers":[],"links":[],"warnings":[{"message":"This service is under construction. You can help through github.com\/CanalTP\/navitia","id":"beta_endpoint"}]}

**Comment by kinnou02** [comment]
You can activate heatmap with configuration in jormungandr: https://github.com/CanalTP/navitia/blob/dev/source/jormungandr/jormungandr/default_settings.py#L111
just set it to `True`, but you will need a "recent" version of boost

**Comment by vg-github** [comment]
Many thanks, sorted!
