### ISSUE TITLE
disable_geojson option not working in journeys service

### ISSUE THREAD

**Issue by ValentinH** [hove-io/navitia#1824]
I have noticed that the disable_geojson is not working for the journeys service. If I set it to true, sections still contains the geojson information.

Example: http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fsandbox%2Fjourneys%3Ffrom%3D2.3749036%253B48.8467927%26to%3D2.2922926%253B48.8583736%26disable_geojson%3Dtrue%26

Duplicated from https://groups.google.com/forum/#!topic/navitia/SgyqaIilyic

**Comment by stifoon** [comment]
Hi Valentin, and tx a lot for the issue.
For your information, I have modified your post only to erase your token ;)

**Comment by ValentinH** [comment]
Actually, it wasn't mine but the one from the Navitia documentation ^^ Taken from: http://doc.navitia.io/#journeys

**Comment by kinnou02** [comment]
Hello,

We didn't implement this parameters on /journeys because we think that most of the the geometry of the journey is needed and is smaller in most of case. But if in your use case the geojson is a problem it's can easily be added

**Comment by pbougue** [comment]
I don't remember we mentioned it especially for `/journeys` even though it might make sense to have it everywhere, as @kinnou02 said.

**Comment by ValentinH** [comment]
Yes, actually it's my bad. I thought I had seen it in the /journeys documentation. But it was somewhere else... Indeed, the geojson parts are not that big and I was just playing to test the different possibilities.

From my side, it's not really needed so don't bother adding it for now if you don't want. ;)
