### ISSUE TITLE
Heat_maps API returns bad durations when parameter "to" defined

### ISSUE THREAD

**Issue by VincentCATILLON** [hove-io/navitia#1861]
Heat maps around: **20 rue Hector Malot, Paris (75012)**
Searching the duration for: **3 rue de Neuilly, Clichy (92110)**

For information, the journey made with "journeys" API for a departure at 8:00 am is: **40/41min**

From URL: **43min** (seems to be normal, for an arrival at 8:43 am)
- /v1/coverage/<coverage>/heat_maps?max_duration=3600&resolution=200&datetime=20161124T080000&from=2.37715%3B48.846781

To URL: **4min** (superman mode)
- /v1/coverage/<coverage>/heat_maps?max_duration=3600&resolution=200&datetime=20161124T090000&to=2.37715%3B48.846781

**Comment by antoine-de** [comment]
closed by #1913 

thanks for the bug report!
