### ISSUE TITLE
build script paris data not found

### ISSUE THREAD

**Issue by yipcma** [hove-io/navitia#1871]
http://data.navitia.io/gtfs_paris_20140502.zip result in 404 Not Found.

Where should i fetch the test data?

Kindly amend. Thanks a lot :)

**Comment by antoine-de** [comment]
we changed our open data web site and forgot to update this script :confused: 

you can grab the data you want here:
https://www.navitia.io/datasets

for the ile de france dataset it's here: https://navitia.opendatasoft.com/explore/dataset/fr-idf/table/?sort=type_file

we need to update the script with a persistent link to a dataset, I'll check how to do this, thanks!
