### ISSUE TITLE
build fail on ubuntu 16.04 internal compiler error on program cc1plus

### ISSUE THREAD

**Issue by yipcma** [hove-io/navitia#1874]
I've been building on ubuntu 16.04 on a ec2 t2.micro with 2GB swap space. All dependencies were installed. But then the at build stage got the following. Any help would be much appreciated.

Scanning dependencies of target ed
[  5%] Building CXX object ed/CMakeFiles/ed.dir/data.cpp.o
[  5%] Building CXX object ed/CMakeFiles/ed.dir/types.cpp.o
[  6%] Building CXX object ed/CMakeFiles/ed.dir/build_helper.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
ptreferential/CMakeFiles/ptreferential.dir/build.make:62: recipe for target 'ptreferential/CMakeFiles/ptreferential.dir/ptreferential.cpp.o' failed
make[2]: *** [ptreferential/CMakeFiles/ptreferential.dir/ptreferential.cpp.o] Error 4
CMakeFiles/Makefile2:1158: recipe for target 'ptreferential/CMakeFiles/ptreferential.dir/all' failed
make[1]: *** [ptreferential/CMakeFiles/ptreferential.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Linking CXX static library libed.a
[  6%] Built target ed
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by antoine-de** [comment]
"2GB swap space" you mean 2GB RAM ?

I don't think it's sufficient to build navitia and thus `cc1` crash.

can you check if it has been killed by your system ? (you can come on irc irc.freenode.org #navitia if you want a more direct conversation)

**Comment by yipcma** [comment]
t2.micro on ec2 comes with 1gb ram, ad i added 2gb swap space.

**Comment by pbougue** [comment]
My understanding on the discussion that ended on irc is we found some improvements to be done on build script for ubuntu 16.04 (to be followed on #1872 ).
And you switched to a "simpler" solution using docker as you have no need to modify the code.
As for the small config build (few RAM, few threads) we probably won't do a thing about that as it's just inherent to the size of the code and the language.

So I close the issue, feel free to reopen it if needed!
