### ISSUE TITLE
Traffic Reports doesn't work

### ISSUE THREAD

**Issue by Diaoul** [hove-io/navitia#1876]
I couldn't get any of the examples in the [Traffic Reports documentation section](http://doc.navitia.io/#traffic-reports) to work.

**Comment by antoine-de** [comment]
I think it's because we don't have any disruptions on the coverage of the documentation :wink: 

if you grab a token for the scnf api (https://data.sncf.com/api) you can try:

https://api.sncf.com/v1/coverage/sncf/traffic_reports

**Comment by Diaoul** [comment]
Thanks I will try that

**Comment by pbougue** [comment]
I close this issue as @antoine-de probably gave a good explanation for that, but feel free to reopen it if needed!
