### ISSUE TITLE
isochrone on docker images

### ISSUE THREAD

**Issue by yipcma** [hove-io/navitia#1905]
I don't seem to find the isochrone endpoint. It'd be great if isochrone is made available on the docker images as well.

**Comment by antoine-de** [comment]
you can activate them with the jormungandr configuration file

in `/srv/jormungandr/settings.py` you need to add `GRAPHICAL_ISOCHRONE = True`

**Comment by yipcma** [comment]
Thanks @antoine-de. Do I need to somehow restart the docker after altering that line? I get the following on the playground:
Status: Message: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again. You have requested this URI [/v1/coverage/default/isochrones] but did you mean /v1/coverage/<region:region>/lines or /v1/coverage/<region:region>/journeys or /v1/coverage/<region:region>/disruptions ? (404), duration of the request: 268ms

**Comment by yipcma** [comment]
this is most strange, now i got {"regions":[{"status":"dead","dataset_created_at":null,"name":null,"start_production_date":null,"shape":null,"end_production_date":null,"error":{"code":"dead_socket","value":"The region default is dead"},"last_load_at":null,"id":"default"}],

**Comment by antoine-de** [comment]
hum you might need to restart apache inside the docker to make it work

**Comment by yipcma** [comment]
I couldn't stop it inside with the init.d. What would be the best command to do so?

**Comment by yipcma** [comment]
the answer is: docker exec [container_id] service apache2 restart
