### ISSUE TITLE
lollipop routes best practice

### ISSUE THREAD

**Issue by yipcma** [hove-io/navitia#1906]
Should this be?
trip1(block1): A B C D A, trip2(block1): A B C D A is about the same as trip1-2(): A B C D A B C D A

**Comment by TeXitoi** [comment]
That's functionally the same. The first solution should be more effective for the routing algorithm. With the first solution, you'll have stay_in sections in journeys.

**Comment by stifoon** [comment]
And the "stay_in" section can reassurate travellers when the bus cuts off its engine for a few minutes.

**Comment by pbougue** [comment]
I guess it can be closed, don't hesitate to reopen it if details are necessary!
