### ISSUE TITLE
Data issues in Berlin

### ISSUE THREAD

**Issue by aardila** [hove-io/navitia#1940]
Hello, we signed up to use your service for a university project in Berlin. It seems that the service only returns walking journeys in Berlin. For example, a request to go from [Berlin's Main Station to the Zoo Station](
https://api.navitia.io/v1/coverage/de/journeys?from=stop_area%3AOBE%3ASA%3ACTP9003201&to=stop_area%3AOBF%3ASA%3ACTP8010406&) suggests a 55-minute walk rather than the [6-minute trip on public transport](http://fahrinfo.bvg.de/Fahrinfo/bin/query.bin/en?SID=A%3D1%40O%3DS%2BU%20Berlin%20Hauptbahnhof%40X%3D13368928%40Y%3D52525849%40U%3D80%40L%3D9003201%40B%3D1%40p%3D1484825155%40%26ZID=A%3D1%40O%3DS%2BU%20Zoologischer%20Garten%20Bhf%20(Berlin)%40X%3D13332710%40Y%3D52506918%40U%3D80%40L%3D9023201%40B%3D1%40p%3D1484825155%40%26getstop=1%26). Curiously, the response states that the (walking) route was created using data from German Railways. You [purportedly have data from the local public transit authority](https://navitia.opendatasoft.com/explore/dataset/de/table/?sort=type_file), so I'm not sure why it would pick walking when it has much shorter transit routes to choose from. We also tried making the request with coordinates instead of stop areas with the same result.

This seems to be widespread in Berlin, as [the isochrone shows that the city centre is not reachable from the airport in less than an hour](https://api.navitia.io/v1/coverage/de/isochrones?boundary_duration%5B%5D=900&boundary_duration%5B%5D=1800&boundary_duration%5B%5D=3600&from=stop_area%3AOBE%3ASA%3ACTP9260024&), which is also incorrect. I understand that the isochrone is in beta, but there seems to be an issue with the underlying data as it would seem to suggest that the calculated times are walking times as opposed to public transport journeys, which are significantly shorter.

Any help would be appreciated. Thanks in advance!

**Comment by antoine-de** [comment]
Hi,

the berlin's dataset does not seem up to date:
http://transitfeeds.com/p/verkehrsverbund-berlin-brandenburg/213/latest

so the routing algorithm can only use the street network :confused:

**Comment by aardila** [comment]
Hi, thanks for the response. So is there no solution? The city of Berlin publishes updates regularly on their [transport page](https://daten.berlin.de/kategorie/verkehr) (in German). The latest dataset (Dec 2016 to Dec 2017) from VBB can be found here: http://www.vbb.de/de/datei/GTFS_VBB_Jan_Dez2017.zip. The linked zip contains 2 other zip files with and without shapefiles.

As I noted in my original message, the [Navitia dataset page for Berlin](https://navitia.opendatasoft.com/explore/dataset/de/table/?sort=type_file) shows that you do have VBB data valid from Dec 2016 to Feb 2017, which is newer than that of transitfeeds.com. So I'm confused: are you using the data that's reported under Datasets, or the feeds in transitfeeds.com? If the former, I see no option for me to provide links to newer datasets...

**Comment by stifoon** [comment]
Hi,
It seems that data have been updated:
https://groups.google.com/forum/#!topic/navitia/WYYOGphtOkY

Journeys seem to combine many operators
http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fde%2Fjourneys%3Fto%3Dstop_area%253AOBF%253ASA%253ACTP8010406%26from%3Dstop_area%253AOBE%253ASA%253A900000180512%26datetime_represents%3Ddeparture%26datetime%3D20170222T120222

And isochrons example:
http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fde%2Fisochrones%3Ffrom%3Dstop_area%253AOBE%253ASA%253A900000180512%26boundary_duration%255B%255D%3D600%26boundary_duration%255B%255D%3D1200%26boundary_duration%255B%255D%3D1800%26boundary_duration%255B%255D%3D2400%26boundary_duration%255B%255D%3D3000%26boundary_duration%255B%255D%3D3600%26

heat_maps:
http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Fde%2Fheat_maps%3Ffrom%3Dstop_area%253AOBE%253ASA%253A900000180512%26resolution%3D200%26max_duration%3D3600%26&

If data are not OK, you can react on the google group forum, the data team checks it very often.
