### ISSUE TITLE
implement and document datetime default value for journeys

### ISSUE THREAD

**Issue by TeXitoi** [hove-io/navitia#1943]
Navitia should propose a default value of datetime for journeys. Naturally, this value should be now.

This is almost the case, but it seems there is a timezone bug.

To fix this issue:
 - [x] journeys without datetime must do the same thing as setting datetime to now;
 - [x] this default value must be documented.

**Comment by yipcma** [comment]
following development on timezone. experience ineffective timezone (specified at agency_timezone, yet navitia seems to treat everything as UTC)

**Comment by pbougue** [comment]
@yipcma Your issue is probably more linked to https://github.com/CanalTP/navitia/issues/1968
