### ISSUE TITLE
Isochrons: circle very far away from the start point sometimes

### ISSUE THREAD

**Issue by jazzzz** [hove-io/navitia#1965]
With some isochron queries, I get a circle thousands of kilometers away from the starting point.

For example, from Bordeaux:

https://api.navitia.io/v1/coverage/fr-sw/isochrones?from=-0.571121470030811%3B44.835845902472045&datetime=20170203T092354&boundary_duration%5B%5D=3600&

![image](https://cloud.githubusercontent.com/assets/290626/22648876/dabd47c8-ec78-11e6-89d3-31175ca0e0a0.png)

![image](https://cloud.githubusercontent.com/assets/290626/22648926/0a55c988-ec79-11e6-913c-54ae3d1a2caf.png)

![image](https://cloud.githubusercontent.com/assets/290626/22648945/2a4f3594-ec79-11e6-9315-f5374b930589.png)

Or from Toulon:

https://api.navitia.io/v1/coverage/fr-se/isochrones?from=5.920332509898633%3B43.13133355367495&datetime=20170201T090000&max_duration=5400&

![image](https://cloud.githubusercontent.com/assets/290626/22649371/e32bf9c0-ec7a-11e6-8047-f5ea49b3830f.png)

![image](https://cloud.githubusercontent.com/assets/290626/22649392/fc8fb82a-ec7a-11e6-8f0c-b30fa590b0ab.png)

![image](https://cloud.githubusercontent.com/assets/290626/22649403/062215cc-ec7b-11e6-8d14-b0ff77cd94ed.png)

**Comment by pbougue** [comment]
This looks like a data problem, especially the [null island](https://en.wikipedia.org/wiki/Null_Island).
Will poke the data team on that, this call enlights even more the problem : https://api.navitia.io/v1/coverage/fr-sw/coord/0%3B0/places_nearby

**Comment by pbougue** [comment]
The second point (in Algeria desert) seems also to be a data problem (harder to detect, probably the Lambert version of null island) : https://api.navitia.io/v1/coverage/fr-se/coord/-3.404569%3B27.140959/places_nearby
Not sure there is much to do on navitia side, other than warn original data providers, though.

**Comment by jazzzz** [comment]
@pbougue ok, thanks!

Do you know where these data come from?

For example, near null island there is the "BORDEAUX - Gambetta Michelet" stop, I could find it in the "Global Transport in South-West region (France)" GTFS file, but not in any other file from
https://navitia.opendatasoft.com/explore/dataset/fr-sw/table/?sort=type_file

```js

      "embedded_type": "stop_area",
      "distance": "0",
      "stop_area": {
        "codes": [
          {
            "type": "external_code",
            "value": "O3322333"
          },
          {
            "type": "source",
            "value": "STOPAREA:22333"
          }
        ],
        "name": "BORDEAUX - Gambetta Michelet",
        "links": [
          
        ],
        "coord": {
          "lat": "0.0",
          "lon": "0.0"
        },
        "label": "BORDEAUX - Gambetta Michelet",
        "timezone": "Europe/Paris",
        "id": "stop_area:O33:SA:22333"
      },
      "quality": 0,
      "id": "stop_area:O33:SA:22333",
      "name": "BORDEAUX - Gambetta Michelet"
    }
```

**Comment by pbougue** [comment]
This is more a discussion on data, so it should more be on the googlegroup (as data analyst read it, and not much issues here). So I will repeat it and reply there, on the specific point of "where does this stop comes from?"
But the idea of the response is... I don't know, I will ask data people. Maybe datasets are not up-to-date, maybe some datasets are missing on navitia.opendatasoft.com.

**Comment by pbougue** [comment]
Closing the subject and following on the googlegroup: https://groups.google.com/forum/#!topic/navitia/-_ZOsfyRRRQ
Don't hesitate to reopen it though if you find something code/dev related about that :)
