### ISSUE TITLE
From where does navitia get gtfs zip files?

### ISSUE THREAD

**Issue by russellhoff** [hove-io/navitia#2081]
I'd like to know which mechanism does navitia use to get all the data, as seen [here](https://navitia.opendatasoft.com/explore/dataset/es/table/?sort=type_file).

**Comment by pbougue** [comment]
Hi, in short we have some private softwares and a dedicated team that manage all those data.
So we (Kisio Digital, ex-CanalTP) try to stay informed of existing opendata feeds (the Navitia googlegroup is a part of that process), and poll those data.
After that we try to test/clean/merge them with "old"/private software, then we use it (navitia.io) and provide the result of those processes as opendata.

**Comment by russellhoff** [comment]
Thank you! I was interested in further knowledge about navitia. Does navitia delete any file within gtfs? Thank you!!

**Comment by pbougue** [comment]
Welcome :)
Actually we more often use a specific format called NTFS (french spec, google translate may help: https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_0.6.md ).
It's close to GTFS, and the differences are more enrichment than deletion (On Demand Transport, those kind of things).
So Navitia is able to eat both GTFS and NTFS, and we provide our opendata pre-processing result in both format on OpenDataSoft.
