### ISSUE TITLE
What is the best way to update /disruptions or /vehicle_journeys?

### ISSUE THREAD

**Issue by chasset** [hove-io/navitia#2200]
Hello, 

How to update our knowledge of the realtime traffic?

The results obtained by API calls looks not ordered. So When I parse once all the pages of /disruptions or /vehicle_journeys, what is the best way to get only the last results since the last call? 

1) Call again all the pages (inefficient)?
2) Call frequently the next page (and loose unordered results)?
3) Add a parameter like `since=20170914T083900`?
4) Other method?

Thanks for your great work.
Best regards,

Pierre-Olivier

**Comment by antoine-de** [comment]
I think the `since` parameter is the right way to go

**Comment by chasset** [comment]
Does it exist yet?

**Comment by pbougue** [comment]
If I'm correct, you should know that this since works on application periods, not update-time...
This update-time filtering is doable, but doesn't exist now.

**Comment by chasset** [comment]
The value of the `since` parameter should be in the application period?

**Comment by antoine-de** [comment]
yes it filters the disruption based on their application period (when they disrupt, not when they have been created/updated)

there are some explanation about the different periods [here](https://github.com/CanalTP/navitia/blob/dev/documentation/rfc/disruptions_periods.md)

So I don't think this parameter is exactly what you were looking for, but unfortunately, for the moment it's not possible to filter the disruption based on their update time

**Comment by chasset** [comment]
Thanks for these explanations.
