### ISSUE TITLE
Add lines object (scheduled or not) on /stop_points

### ISSUE THREAD

**Issue by sign0** [hove-io/navitia#2223]
Convenient to store for example the stop_points/stop_areas and their multiple relations (lines/routes) in offline.

Example (with https://github.com/CanalTP/navitia/issues/2222 PMR Pull request idea) : 

> http://api.navitia.io/v1/coverage/XXX/stop_points/?depth=3

```
{
	"codes": [...],
	"name": "XXX",
	"links": [...],
	"coord": {...},
	"label": "XXX",
	"equipments": [...],
	"administrative_regions": [...],
	"id": "XXX",
	"stop_area": {...},
	"lines": [
		"scheduled": true,
		"vehicle_journeys_statistics": {
			"nb_vehicle_journey_day_prm": 10,
			"nb_vehicle_journey_day_not_prm": 90,
			"nb_vehicle_journey_day_total": 100
		},
		"code": "XXX",
		"network": {...},
		"links": [...],
		"color": "000000",
		"routes": [...],
		"geojson": {...},
		"text_color": "FFFFFF",
		"physical_modes": [...],
		"codes": [...],
		"closing_time": "000000",
		"opening_time": "000000",
		"commercial_mode": {},
		"id": "XXX",
		"name": "XXX"
	]
}
```

**Comment by pbougue** [comment]
This would probably be routes (maybe including lines), not lines directly.
And we have to see what fields are necessary, we don't want to output a too heavy feed.

**Comment by TeXitoi** [comment]
That's not a viable solution. If we go this way, we should includes all the object that can be related to an object, and there is a lot (everything is connected!).

That would need something like GraphQL, and that's not for now.

**Comment by sign0** [comment]
I know everything is connected :)

You can easily display the stops on a map, but without the network + physical_mode and the line_code/line_name, it's quite complicated to differentiate them (bus stop, subway stop, etc.), to show icons like CityMapper for example.

![22403913_10213525770474236_1140364908_o](https://user-images.githubusercontent.com/6769414/31401799-3f0cfa92-adf4-11e7-8a35-113d0dd835ba.jpg)

**Option 1 :** /coords/0.0;0.0/stop_points?distance=1000 + [forEach stops] /stop_points/<stop_id>/lines
- Many queries for nothing.

**Option 2 :** /coords/0.0;0.0/lines?distance=1000
- Lots of data for nothing (stops outside the bbox)

**Option 3 :** /coords/0.0;0.0/stop_points?distance=1000 + /coords/0.0;0.0/lines?distance=1000
- Lots of data for nothing (stops outside the bbox) + matching lines with the stops.

**Option 4 :** Make an external cache
- My current solution

... A simple sliding of the map restart all the requests ...

I really think the ideal would be a depth=4 with filters in the parameters to be able to hide fields. 
Example : **?depth=4&filter=stop.lines.geojson,stop.lines.routes.geojson**
So, everyone would be happy : depth=3 would not be overloaded, and depth=4 would be more complete for the differents use-cases.

**Comment by sign0** [comment]
![capture d ecran 2017-10-10 a 20 29 13](https://user-images.githubusercontent.com/6769414/31403593-c9e582ce-adf9-11e7-8df8-36ec6c6e2ac9.png)

Hmmm : The physical_modes and commercial_modes fields in /stop_points are they recent ? 😆

**Comment by pbougue** [comment]
I don't understand how it is linked to the previous conversation... If it is not we should open a separate issue.
Otherwise everyone will just loose any interest in the primary subject.
