### ISSUE TITLE
gtfs2ed - Problème avec les calendriers

### ISSUE THREAD

**Issue by cvenet30980** [hove-io/navitia#2224]
Lors de l'intégration j'obtiens les messages suivants
INFO - 0 vehicle journeys have been matched to at least one calendar
WARN - no calendar found for 25 vehicle journey
alors que j'ai un calendrier

**Comment by pbougue** [comment]
Il faudrait voir tes données, mais il est probable que ton calendrier soit pas référencé par les 25 trips en question.

**Comment by cvenet30980** [comment]
exemple de trip
route_id,service_id,trip_id,direction_id,shape_id
11,24,11_10101,0,A09011101
et calendar
service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
24,1,1,1,1,1,1,0,20170601,20171231

je ne comprends pas

**Comment by pbougue** [comment]
étrange effectivement, ton calendar est peut-être filtré pour une raison ou une autre... si ton instance répond, et que tu fais un v1/default/status ça te donne une période de validité qui intersectent la période de ton calendar? tu as des /vehicle_journeys par ailleurs?
Sinon, va falloir regarder les autres traces de près lors de l'intégration en particulier.
Ou comparer avec un autre jeu de données qui fonctionne...

**Comment by cvenet30980** [comment]
La start date production est 20170601
La end date production est 20171231
Tout comme mon calendrier

justement, comment obtenir les traces ?
Avez vous un jeu de données light qui fonctionne ?

**Comment by cvenet30980** [comment]
J'ai remarqué dans le code que lors de l'intégration dans le fichier data.cpp on vérifiait que pour un vj (trip) il existait bien un calendrier associé à la ligne du trip
grosso modo on teste calendars->calendar->line_list
sauf erreur de ma part, je ne vois pas où l'on charge la liste des lignes associées à un calendar, mais bon, je ne suis pas un pro du cpp

**Comment by eturck** [comment]
Bonjour,

Ce message est lié aux [grid_calendar du ntfs](https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_0.6.md#grid_calendarstxt-optionnel) et n'a normalement aucun impact sur l'import d'un GTFS.
Sur notre instance de prod où on ne fait pas de grid_calendar on a la même chose : 
```
INFO - 0 vehicle journeys have been matched to at least one calendar
WARN - no calendar found for 30901 vehicle journey
```

C'est simplement pour lier des lignes à des calendriers type "lundi à vendredi" ou trucs du genre, notamment pour de la création de fiches horaires. Et du coup c'est tout à fait normal sur un import GTFS, qui ne peut de toute façon pas avoir ces fichiers !

**Comment by cvenet30980** [comment]
Dans le GTFS, les notions de lundi à dimanche existent aussi dans les calendriers.

Sont elles bien gérées ?

**Comment by eturck** [comment]
Le GTFS a effectivement ces notions de jours de circulation au niveau des services, et oui ça fonctionne très bien dans navitia. 
Le WARN fait référence à une notion équivalente sur les lignes totalement indépendante du GTFS (le fait que le warning apparaisse à l'utilisation de gtfs2ed est simplement du au fait qu'une partie du code est partagée entre l'import du GTFS et du NTFS dans navitia, étant donné que NTFS est une [grosse] extension du GTFS).

**Comment by cvenet30980** [comment]
Merci pour vos réponses
