### ISSUE TITLE
Adding GFTS data of PACA public transports

### ISSUE THREAD

**Issue by remontees** [hove-io/navitia#2227]
Hello!

Could you add these data to Navitia : http://opendata.regionpaca.fr/donnees/detail/lignes-expresses-regionales-et-chemins-de-fer-de-provence-horaires-points-darret-et-lignes.html ?
In fact, I tried to find a journey for example between Grenoble and Briançon but Navitia didn't mentionned the LER between these two cities but only the TER option one. So I think these data aren't integrated into Navitia.

Regards

**Comment by pbougue** [comment]
Hello,
I close this issue and open a conversation on the googlegroup https://groups.google.com/forum/#!forum/navitia as the discussions about data are there and our data-team is following subjects there.
Googlegroup feed: https://groups.google.com/forum/#!topic/navitia/_2yWd-GUTUo
