### ISSUE TITLE
Limit date_times on stop_schedules (filter operator or depth=2)

### ISSUE THREAD

**Issue by sign0** [hove-io/navitia#2232]
If it does not already exist, it would be cool to have an operator on the filter parameter  to define a count (limit) on an json array.

For example to get the next 3 departures of each stops in an area, without geojson route :
**.../coords/2.35911;48.87663/stop_schedules?distance=1000&disable_geojson=true&filter=date_times<4**

Or a depth=2 with 3, 5 or 10 departures ?

In any case, it would be very convenient..

**Comment by TeXitoi** [comment]
`items_per_schedule` must be what you are looking for.

https://api.navitia.io/v1/coverage/fr-idf/coord/2.35911%3B48.87663/stop_schedules?distance=1000&disable_geojson=true&items_per_schedule=3

**Comment by sign0** [comment]
That's exactly what I wanted !
Thanks for the help, and sorry for not having seen it before in the documentation...
