### ISSUE TITLE
Desactivate min_mode rules when we have only one fallback mode

### ISSUE THREAD

**Issue by TeXitoi** [hove-io/navitia#2235]
If we ask for a journey with `first_section_mode[]=bike` and that the solution have less than `min_bike` bike duration, we will filter every solution. Same with car.

These constraints of minimal duration only have sense if we have another fallback mode (as walking). They must be deactivated in such cases.

Googlegroup conversation: https://groups.google.com/forum/#!topic/navitia/JxR2Eo-lHeY

**Comment by pbougue** [comment]
The solution is probably to deactivate these rules when walking is not possible
