### ISSUE TITLE
[Isochrones] Status: Error: no origin point nor destination point

### ISSUE THREAD

**Issue by brylie** [hove-io/navitia#2254]
I am trying to construct an Isochrones request on the Navitia playground. I modify the example request, changing only the `from` parameter, and get the following error:

```
Status: Error: no origin point nor destination point
```

See settings in the following screenshot:
![screenshot from 2017-11-24 11-42-42](https://user-images.githubusercontent.com/17307/33204688-f84310ba-d10c-11e7-850a-f73479dafde8.png)

**Comment by TeXitoi** [comment]
The coverage sandbox is a small and fictive dataset to test the API. It's only on Paris.

You can create a real token (free for less that 90000 requests/month) at https://navitia.io and then do your isochrone on coverage fi:

http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Ffi%2Fisochrones%3Ffrom%3D24.93%253B60.16%26boundary_duration%255B%255D%3D600%26boundary_duration%255B%255D%3D1200%26boundary_duration%255B%255D%3D1800%26boundary_duration%255B%255D%3D2400%26boundary_duration%255B%255D%3D3000%26boundary_duration%255B%255D%3D3600%26

**Comment by brylie** [comment]
Thanks for your support @TeXitoi. I was able to get the Isochrones to generate for Finland. Kiitos!
