### ISSUE TITLE
[Color issue] Background color and text color of some lines are the same 

### ISSUE THREAD

**Issue by TaugyStyle** [hove-io/navitia#2281]
Hi , if someone is able to help , thanks in advance :)
![navitiabug2](https://user-images.githubusercontent.com/17199988/34613255-77ef1818-f22d-11e7-854c-0cea0f460ad3.png)
See black text on black background

**Comment by pbougue** [comment]
Looks like the data provided by Ile de France mobilité are not great on that...
We will warn our data team on that, we might also test it in Navitia, but I'm not sure it's Navitia's role to choose who's right between background and text color.
Any opinion @TeXitoi @kinnou02 @xlqian ?

**Comment by TeXitoi** [comment]
My opinion is that if some data are give to navitia, we don't modify them. Thus, in this case, that's not a navitia bug for me. That's indeed a data bug that we need to fix.

**Comment by TaugyStyle** [comment]
Thanks guys , keep the great work.

**Comment by stifoon** [comment]
So, we won't fix !
