### ISSUE TITLE
Front-End for DataBase

### ISSUE THREAD

**Issue by cvenet30980** [hove-io/navitia#2310]
Is there a front to update the database ED?

Thks

**Comment by kinnou02** [comment]
A front?
ED database is upgraded with alembic from here: https://github.com/CanalTP/navitia/tree/dev/source/sql

**Comment by cvenet30980** [comment]
Update the data of course not the scheme of the database...

**Comment by kinnou02** [comment]
that what [tyr](https://github.com/CanalTP/navitia/tree/dev/source/tyr) does by running *2ed binaries.
it works by watching directories or by posting data to the API.

**Comment by cvenet30980** [comment]
i use *2ed for import osm and gtfs but i want to know if a front web exist to view and/or update data in database like synthese chouette...

**Comment by kinnou02** [comment]
There is no way to view or update data from ED.
We may delete the ED database completely in the future since we doesn't really need it anymore.

**Comment by cvenet30980** [comment]
Ok thks for your answer.
