### ISSUE TITLE
Missing results in kraken planner

### ISSUE THREAD

**Issue by vpassama** [hove-io/navitia#2392]
Hi,

As discussed with @kinnou02 this week, we may have encountered a bug in the routing part of kraken, and it may be a known one due to some problems with walking parts of journeys and raptor implementation. We still don't know if it's really this one so I'll explain it here.

In summary, this is about missing results when requesting kraken planner service, these results aren't returned by kraken until the request's parameter "datetime" is close enough to the departure time of the trips involved.

So, it happens on journeys API and it involves datetime parameter.
The request is simple: 
`/journeys?from=1.445891;43.600563&to=1.446421;43.609092&datetime=2018-04-12+17:36:00&forbidden_uris[]=commercial_mode:1&forbidden_uris[]=commercial_mode:2&count=2`

We have a custom scenario, so the count=2 will induce 2 requests to kraken. The scenario picks the best result matching a profile for each pull of results. In this request (forbidden metro/tramway and departure at 17:36:00GMT+2), the two results from kraken are: 

```
PULL 1 (datetime at 17:36:00)

journey 1-0: 12T15:43:49 -> 12T15:56:21 - 0:12:32 (0:00:32 map) | (W - line:15 (vehicle_journey:550072) - W)
journey 1-1: 12T15:36:00 -> 12T15:50:49 - 0:14:49 (0:14:49 map) | (W)

PULL 2 (datetime at 17:43:50 as journey 1-0 is chosen in first pull)

journey 2-0: 12T15:51:49 -> 12T16:04:21 - 0:12:32 (0:00:32 map) | (W - line:15 (vehicle_journey:549656) - W)
journey 2-1: 12T15:47:49 -> 12T16:02:41 - 0:14:52 (0:02:52 map) | (W - line:171 (vehicle_journey:464570) - T - . - line:144 (vehicle_journey:443617) - W)
journey 2-2: 12T15:45:29 -> 12T16:02:41 - 0:17:12 (0:03:12 map) | (W - line:7 (vehicle_journey:570237) - . - line:144 (vehicle_journey:443617) - W)
journey 2-3: 12T15:45:29 -> 12T16:01:46 - 0:16:17 (0:08:17 map) | (W - line:7 (vehicle_journey:570237) - W)
journey 2-4: 12T15:43:50 -> 12T15:58:39 - 0:14:49 (0:14:49 map) | (W)
```

So our scenario will pick these ones: 
```
journey 1-0: 12T15:43:49 -> 12T15:56:21 - 0:12:32 (0:00:32 map) | (W - line:15 (vehicle_journey:550072) - W)
journey 2-3: 12T15:45:29 -> 12T16:01:46 - 0:16:17 (0:08:17 map) | (W - line:7 (vehicle_journey:570237) - W)
```

Now if I change the datime to 17:37:00GMT+2: 
`/journeys?from=1.445891;43.600563&to=1.446421;43.609092&datetime=2018-04-12+17:37:00&forbidden_uris[]=commercial_mode:1&forbidden_uris[]=commercial_mode:2&count=2`

Kraken will answer: 

```
PULL 1 (17:37:00)

journey 1-0: 12T15:43:49 -> 12T15:56:21 - 0:12:32 (0:00:32 map) | (W - line:15 (vehicle_journey:550072) - W)
journey 1-1: 12T15:39:49 -> 12T15:54:41 - 0:14:52 (0:02:52 map) | (W - line:171 (vehicle_journey:464961) - T - . - line:84 (vehicle_journey:449357) - W)
journey 1-2: 12T15:38:11 -> 12T15:54:41 - 0:16:30 (0:11:30 map) | (W - line:84 (vehicle_journey:449357) - W)
journey 1-3: 12T15:37:00 -> 12T15:51:49 - 0:14:49 (0:14:49 map) | (W)

PULL 2 (17:39:50)

journey 2-0: 12T15:43:49 -> 12T15:56:21 - 0:12:32 (0:00:32 map) | (W - line:15 (vehicle_journey:550072) - W)
journey 2-1: 12T15:39:50 -> 12T15:54:39 - 0:14:49 (0:14:49 map) | (W)
```

And our scenario will pick:

```
journey 1-1: 12T15:39:49 -> 12T15:54:41 - 0:14:52 (0:02:52 map) | (W - line:171 (vehicle_journey:464961) - T - . - line:84 (vehicle_journey:449357) - W)
journey 2-0: 12T15:43:49 -> 12T15:56:21 - 0:12:32 (0:00:32 map) | (W - line:15 (vehicle_journey:550072) - W)
```

So we see here two results are not provided by kraken until the datetime is close enough:

```
journey 1-1: 12T15:39:49 -> 12T15:54:41 - 0:14:52 (0:02:52 map) | (W - line:171 (vehicle_journey:464961) - T - . - line:84 (vehicle_journey:449357) - W)
journey 1-2: 12T15:38:11 -> 12T15:54:41 - 0:16:30 (0:11:30 map) | (W - line:84 (vehicle_journey:449357) - W)
```

And this is weird because these results are actually good ones.

I made 2 NTFS archives, they contain services for today only (2018-04-12) and with only the lines used to provide PT solution in the example request (7 lines).
As I made this, the bug disappeared, I managed to make it appear again by adding one random line in the NTFS even if this line is not involved at all in the solutions.

NTFS without the bug:
[ntfs-without-l15.tar.gz](https://github.com/CanalTP/navitia/files/1902599/ntfs-without-l15.tar.gz)

NTFS with the bug:
[ntfs-with-l15.tar.gz](https://github.com/CanalTP/navitia/files/1902598/ntfs-with-l15.tar.gz)

Just in case, I used this OSM file [midi-pyrenees](http://download.geofabrik.de/europe/france/midi-pyrenees-latest.osm.pbf).

Thank you.

**Comment by kinnou02** [comment]
Hi,

Sorry for the delay, we have talked a little bit of this issue before but we forgot to respond. @TeXitoi sugested that it was caused by the number of second pass, that is 0 by default. You can increase the number of second pass with this parameter: https://github.com/CanalTP/navitia/blob/dev/source/jormungandr/jormungandr/interfaces/v1/Journeys.py#L468
It isn't yet configurable in jormungandr, but we plan to do it soon.

**Comment by kinnou02** [comment]
I tested localy and it seems to fix your problem:
```
/journeys?from=1.445891;43.600563&to=1.446421;43.609092&datetime=2018-04-12+17:36:00&forbidden_uris[]=commercial_mode:1&forbidden_uris[]=commercial_mode:2&count=2&_max_extra_second_pass=100
```

**Comment by vpassama** [comment]
Ok thank you both for your time passed on this issue. I tested it and it works with a second_pass at 2.
I'm just a bit concerned about this value and what would be the best safe/fast value to get rid of this kind of problems. Do you plan to write some documentation to summarize what this parameter do or would you explain it briefly ? I looked a bit at raptor "compute_all" function in the code and I admit I didn't get everything :)

**Comment by TeXitoi** [comment]
Basically, it searches harder for walking alternatives. With a value of 0, we can loose interesting solutions with a bit of walking at the end, but much less at the beginning, making the total walking duration interesting. 

Because, in certain degenerated cases, it can be costly, it's bounded. a value of 10 or 20 is of no harm. Kraken has debug logs around that, telling how many extra second pass it can do, and how many it does.

**Comment by vpassama** [comment]
Ok thank you for the explanation, I think we're good with this information.
