### ISSUE TITLE
Changes in traffic reports / Line section display

### ISSUE THREAD

**Issue by vpassama** [hove-io/navitia#2448]
Hi.

More a discussion than an issue here.

We're currently working on some changes about the line section and how they're displayed in traffic reports and stop schedules.

We explained to @kinnou02 2 needs we have : 

1. the disruptions should be displayed in /lines/{line_id}/stop_schedules even if they are line sections
2. the impacted lines should be listed in traffic_reports also when the disruption is a line section

For the first point, we found that the line sections messages are hidden in specific cases so they can't appear in stop schedules. It is handled by the DisplayLineSectionMessage option which is at 'No' by default. 

Looking at the [documentation](https://github.com/CanalTP/navitia/blob/dev/documentation/rfc/line_sections.md), we decided to remove this option and keep only DisplayMessage option.

After doing this, the good part is that line sections now appear in stop_schedules as we wanted but the bad part is that some tests are broken because they also appear elsewhere, and we want to see with you if it is a problem or not.

So here is a list of what has changed after removing the option, looking at the jormungandr  line_sections_tests: 

- in journeys, line section disruption is displayed if a stop is impacted even if it is not on the same vj as the one used in the journey
(link is at the stop point object in from/to sections, or display_information for a pt section of the journey)
- the line section is displayed in /stop_areas/stopA/stop_schedules even if the stopA is not part of the line section (link is in the line object)
- the line section is displayed in /stop_areas/stopA/departures even if the stopA is not part of the line section (link is in the line object)

The impacted IDs have changed after this modification, the thing is, the impact is now on VJs + stop points + lines as before it was only on VJs.

If you need further details, please tell me. Thank you.

**Comment by TeXitoi** [comment]
The 3 points are regressions for us. We did explicit evolutions to remove these messages.

Some related PR:
 - https://github.com/CanalTP/navitia/pull/2247
 - https://github.com/CanalTP/navitia/pull/2270

If I remember well, we output line sections in stop_schedules if the route point is impacted by the line section. Is it what you want to change, i.e. always show line sections corresponding to the line of the route point, even if the route point is not directly impacted?

**Comment by vpassama** [comment]
No, our need is really simple, when we look at the request /lines/line/stop_schedules, we want the line_section to appear if there is a line_section on some stops as it is not the case for now.

We discussed about this with @kinnou02 today, and we agreed too that the listed changes are regressions.

The idea now is : 

- don't change anything about how the disruptions are linked to objects (stops)
- manage the filters in other way by adding the route context for /departures, /stop_schedules, /journeys etc... Filtering by route when retrieving the disruptions should be enough to handle the problem
- do not touch to the 'basic' pt_ref requests as it shouldn't be a problem if there is no specific filter in them

**Comment by vpassama** [comment]
As this question is managed in an other [PR](https://github.com/CanalTP/navitia/pull/2547), I close this issue.
