### ISSUE TITLE
Inconsistencies in public transport modes

### ISSUE THREAD

**Issue by JanJakes** [hove-io/navitia#2472]
According to the docs [here](https://github.com/CanalTP/navitia/blob/e64980568abcad5872ddfcf3b562f50236554149/documentation/slate/source/includes/objects.md#physical-mode) there is a list of valid physical modes.

However, for some GTFS files the `/journey` endpoint returns modes that are not on the list, such as "Tram". It seems to come from [this part of the code](https://github.com/CanalTP/navitia/blob/6d1eb0aa209af42151ed7c30ebcbba9a38cbe5d8/source/ed/connectors/gtfs_parser.cpp#L1122-L1189) or maybe [this one](https://github.com/CanalTP/navitia/blob/64fddf67611367fec54474d457df31eb60c8d41e/source/ed/build_helper.cpp#L659-L713).

Is it a bug? Is there any complete list of physical modes Navitia can return? Thanks.

**Comment by pbougue** [comment]
Hello Jan,

You seem to be right about this (old) GTFS parsing bug.
To be honest, we don't use GTFS much here so output doc and rules may have evolved and we forgot to maintain that part of the code.

The [list from the doc](https://github.com/CanalTP/navitia/blob/dev/documentation/slate/source/includes/objects.md#physical-mode) you are providing is supposed to be complete and match the one from NTFS (our main format : doc is available [here](https://github.com/CanalTP/navitia/blob/dev/documentation/ntfs/ntfs_fr.md#physical_modestxt-requis), only French).
This list may evolve however, so be prepared for that (we try to think and send a message on the googlegroup when that happens).

Conclusion :
From informations I gathered, we should update that mapping (and refactor so we share code).
But not only `Tram` is wrong and should be renamed `Tramway`, `Rail` also and should be renamed `Train` to follow that list.

Before we work on this, some questions @prhod (who has the main part of the knowledge on data mapping):
Is my conclusion OK for you?
Am I missing something else that we could improve on that mapping?

Nota: Some other (sometimes related) questions are listed in JIRA https://jira.kisio.org/browse/NAV-1562

**Comment by prhod** [comment]
Hi,
I agree with your aswer @pbougue, this parser seems a bit out of date. Is there a way to avoid having maintenance on 2 GTFS parsers (I'm referring to the work around navitia_model) ?

**Comment by JanJakes** [comment]
I just found another weird mode combination, request is http://api.navitia.io/v1/journeys?from=9.1755395;45.4683915&to=8.2982082;46.1039146&datetime=2018-07-27T13:00:00.000, see below:

![download 1](https://user-images.githubusercontent.com/141436/43836005-3b194482-9b14-11e8-85bd-e6072d284131.png)

**Comment by pbougue** [comment]
Ah thanks Jan for those, they are linked to what we internally tracked that's related to that subject!
It will be managed once we make some choices about how we fix this, then we will do a PR (there is also probably some work to do on our internal data management processing).

**Comment by JanJakes** [comment]
Now, on v2.62.0 I'm getting some `physical_mode:NA` when it seems to be a metro. Request https://api.navitia.io/v1/journeys?from=24.9417072;60.1716182&to=24.9040061;60.1616334 & see image below.

![screen shot 2018-09-12 at 15 32 01](https://user-images.githubusercontent.com/141436/45428207-0f733b00-b6a1-11e8-947a-4c8281850c58.png)

Also, note that commercial mode in links is different from commercial mode in display info.

**Comment by pbougue** [comment]
Hello Jan,
The commercial mode is actually the same but Navitia uses the name in display_informations: 
https://api.navitia.io/v1/coverage/fi/commercial_modes/commercial_mode%3AOKA1
As for the physical_mode, the issue is more probably on the data generation on our side, but before Navitia (maybe even in original GTFS). I'll mention it to the team in charge of it and hope they can solve it!

**Comment by pbougue** [comment]
Hey Jan,
It was indeed an issue on the data generation before Navitia. It should now be solved for Finland, and the data team is now checking the rest of the regions to see if there might be the same issue.

As a side note, we try to track data issues more in the [googlegroup](https://groups.google.com/forum/#!forum/navitia) when it's obvious. 
In that case though, it was not obvious, and there is still some work to be done on this issue, for the GTFS mapping inside Navitia :wink:
