### ISSUE TITLE
Navitia failing to find metro tranfers

### ISSUE THREAD

**Issue by JanJakes** [hove-io/navitia#2478]
Navitia's `/journey` endpoint seems to fail to find transfers in some metro stations. It may be related to underground walking transfer missing as a path in OSM or something like that.

Example: http://api.navitia.io/v1/journeys?from=19.060351;47.517769&to=19.02345;47.46578&datetime=2018-07-27T13:00:00.000

The first result looks something like this (blue=bus, yellow=~~metro~~, acutally it is a tram):

![screen shot 2018-07-27 at 15 19 05](https://user-images.githubusercontent.com/141436/43322962-8c61ef3c-91b0-11e8-9ec9-044ba20d8cbd.png)

The best way would however be something like Google shows - two metro lines, almost no walking:

![screen shot 2018-07-27 at 15 19 22](https://user-images.githubusercontent.com/141436/43322972-909b4e2c-91b0-11e8-9ce9-529b4b265650.png)

If we zoom-in on Google, we'll see where the transfer problem may be:

![screen shot 2018-07-27 at 15 19 37](https://user-images.githubusercontent.com/141436/43322981-96abd020-91b0-11e8-9390-614c9c0aebf4.png)

In Prague for instance (trying data from https://transitfeeds.com/p/praha/801) Navitia fails to compute any metro transfer even though it's the best option (and much faster than the actually found one).

I notice Navitia has something like `free_radius_from` and `free_radius_to`, wouldn't a similar logic for transfers help to resolve this issue?

**Comment by JanJakes** [comment]
Now I noticed the yellow line in the first image is not even metro - it seems Navitia simply doesn't compute transfer to metro in this case. However, here metro is used: http://api.navitia.io/v1/journeys?from=19.060507;47.496154&to=19.02345;47.46578&datetime=2018-07-27T15:09:00.000

**Comment by pbougue** [comment]
Hello Jan,

Navitia doesn't (ever) compute transfers. These are left to the choice of the data provider.
One have to provide a transfers.txt file to have transfers (and a complete one if possible).
There are some tools to generate transfers, https://github.com/CanalTP/transfe_rs (a toy-project for Rust here) is one of them.
This explains why we can use Metro directly but not transfer to it.

So this is a data issue, and I will close and move the subject to our googlegroup, where data team can follow issues (only developpers are working on this repository)

**Comment by pbougue** [comment]
Note that we recommend using "`/coverage/hu`/journeys" in requests as it speeds up the discovery and the no-coverage requesting is not closely supported.

**Comment by pbougue** [comment]
Here is the googlegroup feed on the subject : https://groups.google.com/forum/#!topic/navitia/OqUL2tq6pVU

Feel free to reopen this issue if needs be.

**Comment by JanJakes** [comment]
Thanks for the clarification. However, one thing is not clear to me - how "transfer" differs from a "walking" section? Why in the case described above Navitia simply doesn't use walking section from one station to another?
