### ISSUE TITLE
Add Denver, CO?

### ISSUE THREAD

**Issue by eeshugerman** [hove-io/navitia#2623]
Sorry if this is the wrong place to request new regions, please direct me to the proper place if so.

GTFS here: http://www.rtd-denver.com/Developer.shtml

I want to use [Transportr](https://transportr.app/), but my region isn't supported. Their documentation says

> The easiest way to add your area to Transportr is to check if its data is already included in Navitia. [. . .] Find out where [the GTFS] is published and then just contact Navitia for them to make this data available via their free web service API. If they stopped adding new areas, you can also host your own Navitia server since it is fully Free Software.

**Comment by pbougue** [comment]
Hello,
We don't have a coverage for Colorado indeed.
We are tracking requests for new coverage on our googlegroup. And Colorado is already requested there: https://groups.google.com/forum/#!searchin/navitia/denver%7Csort:date/navitia/MItKkKaSapk/kJzpcPSpDAAJ
So I add a little mail about your request there to keep track of all at the same place, and let our data team reply if there are some news.

Closing this issue, but feel free to reopen it.

**Comment by eeshugerman** [comment]
:+1: thanks!
