### ISSUE TITLE
Super-long walking sections

### ISSUE THREAD

**Issue by iserpent** [hove-io/navitia#2685]
Some journey responses may contain very long walking sections ~60km, e.g. [this route](http://canaltp.github.io/navitia-playground/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2Ffr-nor%2Fjourneys%3Ffrom%3D-0.3412369892417644%253B49.178611910546344%26to%3D-0.8745964246919584%253B48.845090536651725%26datetime%3D20190225T080000%26datetime_represents%3Ddeparture%26allowed_id%255B%255D%3Dphysical_mode%253ABus%26)
![navitia_web_ui](https://user-images.githubusercontent.com/5539949/53189785-8f1a1400-3608-11e9-88fe-1cf407e265eb.png)
It is reproducible on some weekdays only (AFAIK).

**Comment by kinnou02** [comment]
Hi,

Good catch! From navitia point view this is a bug in the data, these sections are transfers that we receive with the dataset. 
I will forward this to our data team, so they can fix the problems.

Just to let you known, support for navitia.io is mostly done on https://groups.google.com/forum/#!forum/navitia 

Thanks for the issue.

**Comment by iserpent** [comment]
Hi Alexandre,
Thanks for the quick response and for the info, good to know!

**Comment by kinnou02** [comment]
Problem have been solve in the data, I close this.
