### ISSUE TITLE
Differences between NTFS specification / fusio2ed / transit_model

### ISSUE THREAD

**Issue by eturck** [hove-io/navitia#2768]
Hello everyone.

We have updated our NTFS exporter for our timetable instance. I found some differences between the specification and what fusio2ed was expecting. I told myself it would better to write an issue instead of just forgetting about them :).
I mention transit_model in the title because it is another implementation of an NTFS importer and we already talked about it when discussing admin_stations with @prhod and @kinnou02.

<table>
  <tr>
    <th>NTFS File</th>
    <th>In spec</th>
    <th>In fusio2ed</th>
    <th>In transit_model</th>
  </tr>
  <tr>
    <td rowspan="2"><b>admin_stations.txt</b></td>
    <td><b>admin_name</b> required</td>
    <td>not implemented</td>
    <td>ok</td>
  </tr>
  <tr>
    <td><b>stop_id</b> required</td>
    <td><b>station_id</b> is used instead of <b>stop_id</b></td>
    <td>ok</td>
  </tr>
  <tr>
    <td><b>grid_calendars.txt</b></td>
    <td><b>grid_calendar_id</b> required</td>
    <td><b>id</b> is used instead of <b>grid_calendar_id</b></td>
    <td rowspan="7">grid_* files not supported yet?</td>
  </tr>
  <tr>
    <td><b>grid_exception_dates.txt</b></td>
    <td><b>grid_calendar_id</b> is required</td>
    <td><b>calendar_id</b> is used instead of <b>grid_calendar_id</b></td>
  </tr>
  <tr>
    <td rowspan="2"><b>grid_periods.txt</b></td>
    <td><b>grid_calendar_id</b> is required</td>
    <td><b>calendar_id</b> is used instead of <b>grid_calendar_id</b></td>
  </tr>
  <tr>
    <td><b>start_date</b> is required</td>
    <td><b>begin_date</b> is used instead of <b>start_date</b></td>
  </tr>
  <tr>
    <td rowspan="2"><b>grid_rel_calendar_line.txt</b></td>
    <td><b>grid_calendar_id</b> is required</td>
    <td><b>calendar_id</b> is used instead of <b>grid_calendar_id</b></td>
  </tr>
  <tr>
    <td><b>line_id</b> is required if <b>line_external_code</b> not present</td>
    <td><b>line_id</b> is not used we can only reference the line by <b>line_external_code</b></td>
  </tr>
  <tr>
    <td><b>grid_rel_calendar_trip.txt</b></td>
    <td>Not in specification</td>
    <td>Imported in fusio2ed, read <b>calendar_id</b> and <b>trip_external_code</b></td>
  </tr>
</table>

I don't know what's the best way to present it but I tried my best. Feel free to add to this if you have other differences or close it if you have this kind of data elsewhere :).

**Comment by prhod** [comment]
Thanks for the issue and the consistency check :+1: 
As you mentioned, grid_* files are not yet supported in transit_model, because we don't need tem for the moment. We will keep the issue open until then, but please tell us if it's a blocking issue at your side !

**Comment by kinnou02** [comment]
Fixed!
