### ISSUE TITLE
Can't look for adresses which are not single integer number

### ISSUE THREAD

**Issue by ghost** [hove-io/navitia#2884]
Directly related with https://github.com/grote/Transportr/issues/618

**Comment by kinnou02** [comment]
This is a know issue that won't be solved here, we are slowly transitioning to https://github.com/CanalTP/mimirsbrunn/
Mimirsbrunn should already handle this case.

**Comment by pbougue** [comment]
I close this issue as it's not gonna be solved in this repository, and the transition to that tool is a work in progress for navitia.io
Feel free to reopen/add if needed!
