### ISSUE TITLE
Migration todo: proj4 macro is deprecated

### ISSUE THREAD

**Issue by crocme10** [hove-io/navitia#2897]
```
/usr/include/proj_api.h:37:2: error: #error 'To use the proj_api.h you must define the macro ACCEPT_USE_OF_DEPRECATED_PROJ_API_H'
```

**Comment by crocme10** [comment]
```
add_definitions("-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H")
```

**Comment by pbougue** [comment]
As discussed aside, it looks like it's an issue related to the compiling on an archlinux platform.
We can either clarify things a bit and add it to a doc or an install script for arch (we have to find where).
Or we can just track here troubleshooting information (and probably close the issue once it's done).

@riendegris I let you precise/edit your comments according to what's best for you (and for anyone new to the issue :wink: )

**Comment by kinnou02** [comment]
It's a bit more complex than that, new version of proj have disabled support for the API we are using, next version will drop it, this will catch us some day.
The point of this issue is to track it, and if possible migrate to the new api.

**Comment by kinnou02** [comment]
Sadly the new API is only available in proj 5 that isn't available in debian 8 that is still a target of navitia.
Once we drop support for debian 8 we will be able to migrate to the new api.

**Comment by azime** [comment]
Corrected in this PR [3289](https://github.com/CanalTP/navitia/pull/3289)
