### ISSUE TITLE
Missing route in es_gtfs.zip

### ISSUE THREAD

**Issue by osoitz** [hove-io/navitia#2906]
Hello,

This route seems to be missing in the es_gtfs.zip file. (I didn't check whether any other route is missing.)
http://transitfeeds.com/p/bizkaibus/653/latest/route/3250

The original source for GTFS files for the area is this:
ftp://ftp.geo.euskadi.eus/cartografia/Transporte/Moveuskadi/

**Comment by pbougue** [comment]
Hello,

We transmitted to our data team.
All those issues on data for navitia.io are tracked more on https://groups.google.com/forum/#!forum/navitia.
They will probably try to respond there if there is a need.
Feel free to drop a word there if needs be.

Issues here are more about technical use of Navitia, and the Navitia software itself.

I close this one, and let our data team handle that (maybe ask for more details if they need some here).
