### ISSUE TITLE
Save a route?

### ISSUE THREAD

**Issue by clemishow** [hove-io/navitia#2909]
Is there is a way to save a route with Navitia cuz ids change all the time? 

https://api.navitia.io/v1/coverage/2.131622;48.803564/stop_areas/stop_area:OIF:SA:2:239/routes/route:OIF:056356005:G/stop_schedules?from_datetime=20190708T185944&items_per_schedule=2&

**Comment by pbougue** [comment]
I close this one, as the question is a duplicate from https://github.com/CanalTP/navitia/issues/2861
