### ISSUE TITLE
GTFS parser has difficulties with stoppoints without stoparea.

### ISSUE THREAD

**Issue by koch-t** [hove-io/navitia#298]
It deletes all the stoppoints with stoparea, resulting in not being able to find stops for a lot of records in stop_times.txt. 
Reading at the code, i think this is only a issue with feeds that do not contain a stoparea for all stops.

**Comment by l-vincent-l** [comment]
The wanted behavior is too create a stop_area for stop_point which don't have one.

This should be done in: https://github.com/CanalTP/navitia/blob/dev/source/ed/connectors/gtfs_parser.cpp in the function StopsGtfsHandler::handle_stop_point_without_area
What is the GTFS file you are using?

**Comment by antoine-de** [comment]
To complete Vincent's answer, we create a stop_area for the stop_points only if no stop_area were provided.

If at least one stop area was in the file we consider a stop_point without a stop_area as not consistent.

If you think this is too harsh, maybe it would be useful to have the possibility to soften the coherence checks with a parameter, but I think the default behavior should be quite strict with the coherence of the imported data.

**Comment by koch-t** [comment]
Thanks for the clarifications on this.

I'm using the GTFS file of The Netherlands (gtfs.ovapi.nl/nl), where there are quite a few stops without stop area's. That is partly because the Dutch IFOPT dataset is still in the development stages at this point. The other reason is that some operator's do not consider a single stoppoint to be a stoparea, this situation can for example occur in a oneway street.

I would suggest to also artificially create stoparea's for feeds where not every stop has a stoparea. I strongly suspect there will be other feeds exported this way.

Oh and i found that piece of code already and last night i made this commit on it, which should have been a pull request already. 
https://github.com/skywave/navitia/commit/f2ba9ecb9261bb128c677c4241a047e09a226e03
