### ISSUE TITLE
Complete quoting for parameters of some CMake commands

### ISSUE THREAD

**Issue by elfring** [hove-io/navitia#313]
Some parameters (like "[${CMAKE_BINARY_DIR}/config.h](https://github.com/CanalTP/navitia/blob/ca49644ac2d1b2ec4114a30796cdbc746891f9d7/source/CMakeLists.txt#L82)" and "[${CMAKE_SOURCE_DIR}/type](https://github.com/CanalTP/navitia/blob/f4ddfb324c6c777c120c5873f449bf4f444ee571/source/type/CMakeLists.txt#L7)") are passed to CMake commands in your build scripts without enclosing them by quotation marks. I see that these places will result in build difficulties if the contents of the used variables will contain special characters like semicolons.

I would recommend to apply [advices from a Wiki article](http://cmake.org/Wiki/CMake/Language_Syntax#CMake_splits_arguments_unless_you_use_quotation_marks_or_escapes.).

**Comment by antoine-de** [comment]
thanks for the tip!

**Comment by elfring** [comment]
Thanks for your improvement of the build scripts.
