### ISSUE TITLE
I can't figure out how to get train ticket price.

### ISSUE THREAD

**Issue by baptisteArno** [hove-io/navitia#3188]
What does it mean if it doesn't get the ticket fare?

![91610232_606429699938839_4645636373397635072_n](https://user-images.githubusercontent.com/16015833/78500319-01d74780-7756-11ea-94f4-4d0b55dd5aa6.png)

**Comment by pbougue** [comment]
Hello @baptisteArnaud,

Here you are using SNCF's API (that's provided through Navitia).
So the best place to ask would be SNCF's support.

Anyway, in Navitia it just means that no fare data exists for this trip.
And as far as I know, you won't find any in SNCF's API, as no fare data is available there.

You can ask them to provide it, but I think it's not part of future plans, as it's a paid service and it's quite complicated given the traveler-profile (age, cards, ...) and it varies with the time (available seats, ...).

So I will close this question, but do not hesitate to reopen it if you have more questions on the fares in Navitia!
