### ISSUE TITLE
N- Voie

### ISSUE THREAD

**Issue by BillAx579** [hove-io/navitia#3284]
Bonjour, 

Je ne voit pas la possibilité de récupérer le numéro de voie des train au départ.. 

Pas disponible ?

Merci !

**Comment by stifoon** [comment]
Bonjour,
je ne sais pas de quelles données tu parles, mais dans tous les cas c'est un problème de data. Il faudrait donc que tu déclare ton problème auprès du transporteur, ou sur le forum https://groups.google.com/forum/#!forum/navitia
Ici, c'est pour déclarer des anomalies sur le software Navitia ;)
Bonne journée !
