### ISSUE TITLE
Data handling

### ISSUE THREAD

**Issue by bgamassa** [hove-io/navitia#3330]
Hello Navitia team, I recently downloaded raw data in NTFS format here: https://navitia.opendatasoft.com/explore/dataset/fr-idf/table/.

I was actually interested in the "stops.txt" file and tried to find a way to link stops to lines, but didn't find any element in the other files to do it. Could you please tell me if it's possible for example to know which stations belong to a specific line ? I sent an email to the team but didn't get a reply.

Thank you very much,
Have a nice day.

**Comment by nonifier** [comment]
Hi,

if you need more information about the NTFS specification, you can have a look at : https://github.com/CanalTP/ntfs-specification/blob/master/ntfs_fr.md. 
It's unfortunately only available in French at the moment, but you may found resources that might help get a better grasp of the format - https://dbdiagram.io/embed/5e218b4a9e76504e0ef05fcd.

Hope this helps

**Comment by bgamassa** [comment]
Thank you very much, it helped me a lot!

**Comment by nonifier** [comment]
You're most welcome :)
