### ISSUE TITLE
Improve documentation of 

### ISSUE THREAD

**Issue by koch-t** [hove-io/navitia#352]
https://github.com/CanalTP/navitia/blob/dev/source/routing/raptor.cpp#L105
Here a 120 is pulled from out of nowhere, my interpretation of it is that it sets what we call at Bliksem slacktime. An extra buffer time between the arrival and any departure, even at the same stop.

If that's the case a feature request: allow the slacktime to be configured by the request. This allows passengers to request extra transfer time, for example if they have lots of baggage.

**Comment by TeXitoi** [comment]
The 120 was removed by https://github.com/CanalTP/navitia/pull/541

Now, you need a transit to itself. Ed add a 120s transit to itself if it do not exists in `navitia::ed::Data::complete()`

**Comment by koch-t** [comment]
Yes
