### ISSUE TITLE
using count in isochrone api

### ISSUE THREAD

**Issue by Azema** [hove-io/navitia#356]
Hi guys,

I've a problem with API journeys:
- The parameter `count` is not used, but it's checked:
  
  http://api.navitia.io/v1/journeys?from=stop_point:ONA:SP:COME3&datetime=20140322100000&count=10
  http://api.navitia.io/v1/journeys?from=stop_point:ONA:SP:COME3&datetime=20140322100000&count=toto
- This API is not paginated ?

Sorry for my English, I prefer the French ;-)

Say hello to everyone for me

**Comment by antoine-de** [comment]
you are right, this api does not seems correctly paginated (the ``count` should be used for that).

Beware that you did not give a `to` param to your journey, thus you don't call the classic 'journey' API but the 'isochrone' API (hence the many journeys returned).

We don't use often this API yet, hence the mistake on the pagination.
Thanks for the issue, we'll try to correct that as soon as possible!
