### ISSUE TITLE
Comment language

### ISSUE THREAD

**Issue by abyrd** [hove-io/navitia#357]
As I'm reading through the source I notice that there is a mix of French and English comments. Has a decision been made to use English as the Navitia working language? If so are you interested in comment translation pull requests?

**Comment by antoine-de** [comment]
Hi Andrew, sorry for the delay, we were in an internal hackaton pluging ducks on arduinos :)

Of course the comments should be in english. All new comments are in english and we try to translate the old ones when changing code around but any help would be appreciated!

**Comment by ChristophePetitjean** [comment]
Hi Antoine, Tx for yrreply. I hope the language choice will not refrain from expressing in detail?

**Comment by antoine-de** [comment]
Hi Christophe, what do you mean by that ?

**Comment by ChristophePetitjean** [comment]
Hi Antoine, sorry for the late reply. See also https://github.com/CanalTP/navitia/issues/6 
So, preferaby English comments etc. indeed but rather have a mix of French and English comments than no comments at all.

**Comment by antoine-de** [comment]
yep you're absolutely right, we need to be careful with that.
