### ISSUE TITLE
Random spots using Ile-de-France Mobilités isochrones

### ISSUE THREAD

**Issue by etienne-delestoile** [hove-io/navitia#3700]
Bonjour,

Pour un projet de recherche, je travaille avec le Calculateur Ile-de-France Mobilités - Accès générique et j’utilise l’API que j’appelle via Python.

J’ai cependant parfois des résultats étranges lorsque je plot les isochrones, avec parfois des isochrones qui font des sortes de taches isolées.

Please find below deux cartes, une avec les isochrones le mardi à 10h et une avec les isochrones le mardi à 18h. Sur la première (T1000), l’isochrone correspondant à 120 minutes est représenté par une petite tache à gauche. Sur la seconde, il est représenté par la tache en bas à droite, tandis que l’isochrone 60 minutes est aussi problématique. Ce qui voudrait dire que le problème change selon le paramètre ‘datetime’ dans l’appel d’API.

Voici le type d’url que j’appelle :
[https://traffic.api.iledefrance-mobilites.fr/v1/mri-isochrones/isochrones?from=2.347555;48.85766&datetime=20220315T1800&max_duration=1200](https://urldefense.com/v3/__https:/protection.retarus.com/v1?u=https*3A*2F*2Ftraffic.api.iledefrance-mobilites.fr*2Fv1*2Fmri-isochrones*2Fisochrones*3Ffrom*3D2.347555*3B48.85766*26datetime*3D20220315T1800*26max_duration*3D1200&c=11PVWQghXP&r=2we3Mu8JzYYgAmTlPsTHok&k=7s1&s=NFmMASPOORCKzwI3JhnFjoGUvgaeiDXyarDoltRdMIT__;JSUlJSUlJSUlJSUlJQ!!PKypRk0JOBI!DvjzYx5q7KZ7Y592G0J916zcHETI9UzbZUiM7DJwV-wFxVWFMG9WXtWN6L2hYWQqq8vSc8X87uvzlhU$)

Many thanks.

![isochrone_T1800](https://user-images.githubusercontent.com/92101923/160806580-08663150-2f36-49e3-b6fd-c0d1ef034ee0.png)

![isochrone_T1000](https://user-images.githubusercontent.com/92101923/160806562-f3355ae9-3f68-4de7-abc1-78917e30b79d.png)

**Comment by stifoon** [comment]
Bonjour,
Les issues sur Github sont réservées aux anomalies logicielles : ton problème est un problème d'intégration.
Tu pourras trouver du support à ces questions
* directement auprès du fournisseur du service que tu utilises : il me semble qu'il y a une page d'aide autour du service que tu utilises https://prim.iledefrance-mobilites.fr/fr/centre-aide
* voire éventuellement sur le forum google group Navitia https://groups.google.com/g/navitia, mais il va falloir que tu postes les URLs d'appel à Navitia avec tes questions : le service que tu utilises n'est pas l'API standard

Bonne soirée !
Stephan
