### ISSUE TITLE
How does Navitia compare to alternatives?

### ISSUE THREAD

**Issue by paro-** [hove-io/navitia#3844]
Hi,

After seeing the listed alternatives (OTP, rrrr, Synthese), do you know how Navitia fare compared to them?
Do you have a performance benchmark, or additional features?

Thanks, kind regards,
Paul

**Comment by stifoon** [comment]
Hi,

there is this benchmark, writed 4 years ago, but you could find some answers : 
https://github.com/hove-io/navitia/wiki/OpenTripPlanner-and-Navitia-comparison.

Main differences are around
* Navitia has the capability to manage multiple coverages through one endpoint
* Navitia can compute multiple alternatives (walk / bike / Public transport / car / etc.) in 1 really fast request
* Navitia is really difficult to install and manage vs OTP, especially if you plug all components

**Comment by stifoon** [comment]
Some precision on the "single endpoint":
It is possible to set up a Navitia platform over a national or an international territory.
This is what we did with api.navitia.io. It means
-  search for data throughout the territory, 
- daily updates : public transport timetables change very oftenly ;
- integration of real-time flows
- many enrichments (stations entrance, etc.)

Then, it is possible to request Navitia only with coordinate

- On Bordeaux https://api.navitia.io/v1/journeys?from=-0.598219%3B44.832927&to=-0.55669%3B44.82527
- On Rennes https://api.navitia.io/v1/journeys?from=-1.67773%3B48.11363&to=-1.66852%3B48.10014
- On Paris https://api.navitia.io/v1/journeys?from=2.35972%3B48.84318&to=2.27457%3B48.83595

This the main interface difference with OTP : OTP needs multiple instances for each territory
