### ISSUE TITLE
Cannot find a region with stop_area:IDFM:74162 and stop_area:STE:OCE87611004 in the same time

### ISSUE THREAD

**Issue by JingLeiTalan** [hove-io/navitia#3877]
Hello,

After testing this API, i had some errors which i can't figure it out. Coud you help me ?

get:  https://api.navitia.io/v1/journeys?from=2.2944813;48.85837009999999&to=1.4537049;43.6113349

Thank you for your help in advance,

BR,

**Comment by pbougue** [comment]
Hello,

It may not be that explicit, but Navitia works with data-regions (calling them coverages) and travelling from one region to the other is not supported.
This separation in region is there to sustain an acceptable level of performances.

Here, it looks like you are trying to go from one region (Paris is in `fr-idf`) to another (Toulouse is in `fr-sw`).
Hence, the error you get.

You may check the shape of the regions using https://playground.navitia.io/play.html?request=https%3A%2F%2Fapi.navitia.io%2Fv1%2Fcoverage%2F%2F%3F (clic "MAP" in the response part).

Also, note that if you have access to sncf API (use dedicated token provided by sncf), the following does work : https://api.sncf.com/v1/coverage/sncf/journeys?from=2.2944813%3B48.85837009999999&to=1.4537049%3B43.6113349&
-> The `sncf` coverage (using navitia under the hood) has almost no urban transportation, but it has country-wide transport from sncf.
