### ISSUE TITLE
Missing submodules

### ISSUE THREAD

**Issue by khamaileon** [hove-io/navitia#4036]
There are 3 submobules in the navitia repository that point to empty repositories. I guess they must have existed under the former organization. Are they still needed?

https://github.com/hove-io/chaos-proto
https://github.com/hove-io/libosmpbfreader
https://github.com/hove-io/prometheus-cpp

**Comment by woshilapin** [comment]
These repositories have been closed, see https://github.com/hove-io/navitia/pull/4037/files. Note that they're still needed for compilation. `navitia` stays open for exploration, but is not buildable from now on.

**Comment by khamaileon** [comment]
Oh, I didn't know that. Is it possible to get a copy of the repository before it's deleted?
