### ISSUE TITLE
Link to OpenDataSoft broken

### ISSUE THREAD

**Issue by amigainc** [hove-io/navitia#4098]
**Describe the bug**
The link to [https://navitia.opendatasoft.com/](https://navitia.opendatasoft.com/) returns a "not found" message.
Is there another way to access data?

**Screenshots**
![image](https://github.com/hove-io/navitia/assets/6299136/76b41f26-35a3-4ee5-9851-ddb5a5ae302c)

**Comment by stifoon** [comment]
Hello [amigainc](https://github.com/amigainc)
This is not a Navitia's bug, but a www.navitia.io question. I let you post your request in the forum, or ask a question by mail there.
Regards,
Stephan
