### ISSUE TITLE
GET Api /coords returns a 403

### ISSUE THREAD

**Issue by amigainc** [hove-io/navitia#4099]
**Describe the bug**
The link below returns a 403 code, even in examples (JSFiddle)

**To Reproduce**
[https://api.navitia.io/v1/coords/5.569052397;46.598515602](https://api.navitia.io/v1/coords/5.569052397;46.598515602)

**Expected behavior**
Should return the region?

**Comment by stifoon** [comment]
(please don't publish your token ;) )

**Comment by stifoon** [comment]
Hello [amigainc](https://github.com/amigainc)
This is not a Navitia's bug, but a www.navitia.io question. I let you post your request in the forum, or ask a question by mail there.
Regards,
Stephan
