### ISSUE TITLE
[SNCF] Issues with /v1/coverage/sncf/journeys

### ISSUE THREAD

**Issue by AdamPeteraDevcors** [hove-io/navitia#4107]
**Describe the bug**
Dear Navitia,
We are facing an issue when retrieving journey info from **_https://api.sncf.com/v1/coverage/sncf/journeys_** for the entry points mentioned below:
_entry point_ (SNCF internal station identifier - carrier)
_stop_area:SNCF:71600000_ (ESMAT - OUIGO)
_stop_area:SNCF:71609110_ (ESALC - OUIGO)
_stop_area:SNCF:71040402_ (ESZAA - OUIGO)
_stop_area:SNCF:71170000_ (ESMCH - OUIGO)
_stop_area:SNCF:71032169_ (ESBAA - OUIGO)
_stop_area:SNCF:71606004_ (ESAAE - OUIGO)
_stop_area:SNCF:80202861_ (DEMPS - Deutsche Bahn)
_stop_area:SNCF:71793150_ (ESAGM - TER)
_stop_area:SNCF:71041046_ (ESTAA - OUIGO)

For all API calls that include those entry points we do receive an error from your end as follows (the example for one of the mentioned case):
_{"error":{"id":"unknown_object","message":"The entry point: stop_area:SNCF:71041046 is not valid"}_

Could you please help us? Should we use different codes?

Thank you so much,
have a nice day,
Adam Petera from OMIO

**Comment by pbougue** [comment]
Hello @AdamPeteraDevcors ,

This topic is related to SNCF API, and probably the content of its data.
So you should contact them through this channel instead: https://numerique.sncf.com/startup/api/support

Here on github we focus on code and functionalities, so I'll close this issue, but feel free to reopen if you think of something that fits here.

Have a nice day
