### ISSUE TITLE
Add terminus name in JSON route object

### ISSUE THREAD

**Issue by aelkhour** [hove-io/navitia#492]
Hello,

Currently a JSON route object contains information about the route name, id and associated line, e.g.

``` json
route: {
  name: "Pont Neuf - Porte de Pantin",
  is_frequence: "False",
  line: {
  comment: "",
  code: "75",
  name: "Pont Neuf - Porte de Pantin",
  color: "ffcd02",
  id: "line:RTP:1125156"
  },
  id: "route:RTP:1125156"
}
```

When using the routes or departures API, it can be very useful to get information about the last stop point of the route, aka terminus.

Would it be possible to provide at least the terminus name in the route object?

Cheers.

**Comment by koch-t** [comment]
Mmh afaik a route can have multiple termini, the Journey_pattern is the object with the fixed sequence of stops

**Comment by aelkhour** [comment]
I see your point, I did not realize that the concept of journey pattern existed in navitia (afaik it is not exposed in the JSON api).

A route denotes a collection of journey patterns matching the same direction. It would then make sense to add this direction information in the route object.
In the above example, the direction would be either "Pont Neuf" or "Porte de Pantin" depending on the route of the "Pont Neuf - Porte de Pantin" line.

Does this request make more sense?

**Comment by jlerpscher** [comment]
+1 
See also https://groups.google.com/forum/#!topic/navitia/zoRo_7scPmw

**Comment by aelkhour** [comment]
Is there an ETA for this issue to be solved?

**Comment by thiphariel** [comment]
They are still in 'preprod'. The 1.1 release on navitia.io is for tomorrow probably :) (The told me that on IRC)
PS : Thanks for this PR, sounds really good ;)

**Comment by aelkhour** [comment]
Great, thanks :-)

**Comment by aelkhour** [comment]
Solved. Closing.

``` json
route: {
    direction: {
        embedded_type: "stop_point",
        stop_point: {
            comment: "1 AV DE LA PORTE DE PANTIN - 93055",
            name: "PORTE DE PANTIN",
            coord: {
                lat: "48.890101",
                lon: "2.396431"
            },
            equipments: [ ],
            id: "stop_point:RTP:SP:3926432"
        },
        quality: 0,
        id: "stop_point:RTP:SP:3926432",
        name: "PORTE DE PANTIN"
    },
    name: "PONT NEUF - PORTE DE PANTIN",
    is_frequence: "False",
    line: {
        comment: "",
        code: "75",
        name: "Pont Neuf - Porte de Pantin",
        color: "ffcd02",
        id: "line:RTP:1154113"
    },
    id: "route:RTP:1154113"
}
```
