### ISSUE TITLE
Update README documentation in source/ed

### ISSUE THREAD

**Issue by pietercolpaert** [hove-io/navitia#6]
README is out of date. Could it be updated? Right now I cannot understand how to get a GTFS dataset into kraken

**Comment by ChristophePetitjean** [comment]
Hi Pieter, see also https://github.com/CanalTP/navitia/issues/357#

**Comment by antoine-de** [comment]
ouch, the file is more than outdated, I didn't even knew it existed...

For the moment the [install file](https://github.com/CanalTP/navitia/blob/dev/install.rst) is better, we will have to rewrite the source/ed/README soon!
