### ISSUE TITLE
ISO8601 datetime

### ISSUE THREAD

**Issue by pietercolpaert** [hove-io/navitia#63]
Bonjour à tous,

http://api.navitia.io/v1/coverage/paris/stop_points/stop_point:RTP:SP:3952734/departures

Est-ce que vous pouvez mettre des `-` et   `:` dans les datetimes? C'est la seule format de iso8601 qui est bien supporté par le javascript des navigateurs.

To be discussed? :)

**Comment by Tristramg** [comment]
Obviously I can’t talk in the name of the developers, but I can comment ;)

It is depressing that to get access to specification you should pay… http://www.iso.org/iso/catalogue_detail?csnumber=40874

Luckily it is easy to find on the internet http://www.uninfo.it/TC154/TC154private/DIS/8601_FDIS.pdf

Navitia uses the basic form of the iso8601 datetime. The document states that the expanded format should be used for plain text.

I think this would dramatically break existing implementations just to go around a crappy implementation of your browser.

Maybe the best would be to used a library that allows you explicitly use the format like http://momentjs.com/

**Comment by antoine-de** [comment]
I do agree with tristram, I thus close this issue

**Comment by Tristramg** [comment]
\o/

**Comment by pietercolpaert** [comment]
Haha. Fair enough ;)
