### ISSUE TITLE
libgoogle-perftools-dev : Ubuntu 12.04 issue

### ISSUE THREAD

**Issue by nicolas-garcia** [hove-io/navitia#698]
Hi !

As discussed on IRC, libgoogle-perftools-dev on Ubuntu 12.04 is in version 1.7 and use deprecated headers since version 2.0.

`navitia/source/kraken/data_manager.hy:37:41: fatal error: gperftools/malloc_extension.h: No such file or directory`
The right path for this version is `google/malloc_extension.h`

Thanks !

**Comment by TeXitoi** [comment]
As we will need a fresher boost, we will not support old gperftools versions.

#1236 will fail the compilation directly during the cmake, which make this depedency more explicit.
