### ISSUE TITLE
findprotoc.cmake / LOG4CPLUS_FIND_QUIETLY

### ISSUE THREAD

**Issue by koch-t** [hove-io/navitia#774]
https://github.com/CanalTP/navitia/blob/dev/source/cmake_modules/FindProtoc.cmake#L13

```
    if(NOT LOG4CPLUS_FIND_QUIETLY)
```

Looks very out of place, copy/paste error?

**Comment by antoine-de** [comment]
yep, seems a bit out of place :smile: 

thanks!
