### ISSUE TITLE
Nearby search doesn't work

### ISSUE THREAD

**Issue by stifoon** [hove-io/navitia#812]
Hi!
One question. The doc page (https://github.com/CanalTP/navitia/blob/dev/documentation/navitia.io/source/integration.rst) states:
get /coverage/lon;lat/collection_name > Collection of objects of a region
and Collections are
- lines
- ...
- stop_points
- stop_areas

However, I cannot seem to be able to get e.g. https://api.navitia.io/v1/coverage/2.6667;48.7667/stop_areas or https://api.navitia.io/v1/coverage/2.6667;48.7667/stop_points to work. I get the error: "No region nor coordinates given"
It should also work with https://api.navitia.io/v1/coverage/2.6667;48.7667/lines.

In the meanwhile, i can use https://api.navitia.io/v1/coverage/2.6667;48.7667/places_nearby?type[]=stop_area&distance=10000 but it is less graceful :D

**Comment by stifoon** [comment]
Documentation has been rewriten, but the issue is still there http://canaltp.github.io/navitia/#public-transportation-objects-exploration

**Comment by kofronpi** [comment]
I'm having a similar problem with HATEOAS links given as a response which are wrong when I query something as `https://api.navitia.io/v1/coverage/2.564097;50.296507`

I can't follow links, it throws this kind of errors:

```
{
  "message": "No region nor coordinates given. You have requested this URI [/v1/coverage/2.564097;50.296507/networks] but did you mean /v1/coverage/<region:region>/networks ?",
  "error": {
    "message": "No region nor coordinates given",
    "id": "unknown_object"
  }
}
```

Something seems off, or the documentation is not up to date ? http://doc.navitia.io/#route-schedules-and-time-tables

**Comment by stifoon** [comment]
Could you please send me the original request which generate the wrong Hateoas link?

I will ask to fix this issue, as I'm not the lonely concerned guy ;)

**Comment by kofronpi** [comment]
@stifoon 

`curl -X GET -H "Authorization: Basic your_token==" -H "Cache-Control: no-cache" -H "Postman-Token: xxxxx" "https://api.navitia.io/v1/coverage/2.564097;50.296507"`

(code generated by Postman as you can see)

**Comment by stifoon** [comment]
Every case are working since places_nearby corrections, few months ago
